// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: monarchic_agent_protocol.proto

package agent_protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRole int32

const (
	AgentRole_AGENT_ROLE_UNSPECIFIED AgentRole = 0
	AgentRole_PRODUCT_OWNER          AgentRole = 1
	AgentRole_PROJECT_MANAGER        AgentRole = 2
	AgentRole_DEV                    AgentRole = 3
	AgentRole_QA                     AgentRole = 4
	AgentRole_REVIEWER               AgentRole = 5
	AgentRole_SECURITY               AgentRole = 6
	AgentRole_OPS                    AgentRole = 7
)

// Enum value maps for AgentRole.
var (
	AgentRole_name = map[int32]string{
		0: "AGENT_ROLE_UNSPECIFIED",
		1: "PRODUCT_OWNER",
		2: "PROJECT_MANAGER",
		3: "DEV",
		4: "QA",
		5: "REVIEWER",
		6: "SECURITY",
		7: "OPS",
	}
	AgentRole_value = map[string]int32{
		"AGENT_ROLE_UNSPECIFIED": 0,
		"PRODUCT_OWNER":          1,
		"PROJECT_MANAGER":        2,
		"DEV":                    3,
		"QA":                     4,
		"REVIEWER":               5,
		"SECURITY":               6,
		"OPS":                    7,
	}
)

func (x AgentRole) Enum() *AgentRole {
	p := new(AgentRole)
	*p = x
	return p
}

func (x AgentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_monarchic_agent_protocol_proto_enumTypes[0].Descriptor()
}

func (AgentRole) Type() protoreflect.EnumType {
	return &file_monarchic_agent_protocol_proto_enumTypes[0]
}

func (x AgentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRole.Descriptor instead.
func (AgentRole) EnumDescriptor() ([]byte, []int) {
	return file_monarchic_agent_protocol_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Role          AgentRole              `protobuf:"varint,3,opt,name=role,proto3,enum=monarchic.agent_protocol.v1.AgentRole" json:"role,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	Inputs        *structpb.Struct       `protobuf:"bytes,5,opt,name=inputs,proto3" json:"inputs,omitempty"`
	Constraints   *structpb.Struct       `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	GatesRequired []string               `protobuf:"bytes,7,rep,name=gates_required,json=gatesRequired,proto3" json:"gates_required,omitempty"`
	RunContext    *RunContext            `protobuf:"bytes,8,opt,name=run_context,json=runContext,proto3" json:"run_context,omitempty"`
	Extensions    *structpb.Struct       `protobuf:"bytes,9,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_monarchic_agent_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_monarchic_agent_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_monarchic_agent_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetRole() AgentRole {
	if x != nil {
		return x.Role
	}
	return AgentRole_AGENT_ROLE_UNSPECIFIED
}

func (x *Task) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Task) GetInputs() *structpb.Struct {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Task) GetConstraints() *structpb.Struct {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Task) GetGatesRequired() []string {
	if x != nil {
		return x.GatesRequired
	}
	return nil
}

func (x *Task) GetRunContext() *RunContext {
	if x != nil {
		return x.RunContext
	}
	return nil
}

func (x *Task) GetExtensions() *structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	TaskId        string                 `protobuf:"bytes,6,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Extensions    *structpb.Struct       `protobuf:"bytes,7,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_monarchic_agent_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_monarchic_agent_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_monarchic_agent_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Artifact) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Artifact) GetExtensions() *structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message       *string                `protobuf:"bytes,6,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Extensions    *structpb.Struct       `protobuf:"bytes,7,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_monarchic_agent_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_monarchic_agent_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_monarchic_agent_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Event) GetExtensions() *structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type GateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Gate          string                 `protobuf:"bytes,2,opt,name=gate,proto3" json:"gate,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Reason        *string                `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	Evidence      *structpb.Struct       `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Extensions    *structpb.Struct       `protobuf:"bytes,6,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateResult) Reset() {
	*x = GateResult{}
	mi := &file_monarchic_agent_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateResult) ProtoMessage() {}

func (x *GateResult) ProtoReflect() protoreflect.Message {
	mi := &file_monarchic_agent_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateResult.ProtoReflect.Descriptor instead.
func (*GateResult) Descriptor() ([]byte, []int) {
	return file_monarchic_agent_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *GateResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GateResult) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *GateResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GateResult) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *GateResult) GetEvidence() *structpb.Struct {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *GateResult) GetExtensions() *structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type RunContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Worktree      string                 `protobuf:"bytes,3,opt,name=worktree,proto3" json:"worktree,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Runner        string                 `protobuf:"bytes,5,opt,name=runner,proto3" json:"runner,omitempty"`
	Labels        []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Extensions    *structpb.Struct       `protobuf:"bytes,7,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunContext) Reset() {
	*x = RunContext{}
	mi := &file_monarchic_agent_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContext) ProtoMessage() {}

func (x *RunContext) ProtoReflect() protoreflect.Message {
	mi := &file_monarchic_agent_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContext.ProtoReflect.Descriptor instead.
func (*RunContext) Descriptor() ([]byte, []int) {
	return file_monarchic_agent_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *RunContext) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RunContext) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RunContext) GetWorktree() string {
	if x != nil {
		return x.Worktree
	}
	return ""
}

func (x *RunContext) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunContext) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *RunContext) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RunContext) GetExtensions() *structpb.Struct {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_monarchic_agent_protocol_proto protoreflect.FileDescriptor

const file_monarchic_agent_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1emonarchic_agent_protocol.proto\x12\x1bmonarchic.agent_protocol.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x9f\x03\n" +
	"\x04Task\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12:\n" +
	"\x04role\x18\x03 \x01(\x0e2&.monarchic.agent_protocol.v1.AgentRoleR\x04role\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12/\n" +
	"\x06inputs\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06inputs\x129\n" +
	"\vconstraints\x18\x06 \x01(\v2\x17.google.protobuf.StructR\vconstraints\x12%\n" +
	"\x0egates_required\x18\a \x03(\tR\rgatesRequired\x12H\n" +
	"\vrun_context\x18\b \x01(\v2'.monarchic.agent_protocol.v1.RunContextR\n" +
	"runContext\x127\n" +
	"\n" +
	"extensions\x18\t \x01(\v2\x17.google.protobuf.StructR\n" +
	"extensions\"\xd9\x01\n" +
	"\bArtifact\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x17\n" +
	"\atask_id\x18\x06 \x01(\tR\x06taskId\x127\n" +
	"\n" +
	"extensions\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"extensions\"\xf3\x01\n" +
	"\x05Event\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\amessage\x18\x06 \x01(\tH\x00R\amessage\x88\x01\x01\x127\n" +
	"\n" +
	"extensions\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"extensionsB\n" +
	"\n" +
	"\b_message\"\xe8\x01\n" +
	"\n" +
	"GateResult\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04gate\x18\x02 \x01(\tR\x04gate\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\x06reason\x18\x04 \x01(\tH\x00R\x06reason\x88\x01\x01\x123\n" +
	"\bevidence\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bevidence\x127\n" +
	"\n" +
	"extensions\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"extensionsB\t\n" +
	"\a_reason\"\xd5\x01\n" +
	"\n" +
	"RunContext\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1a\n" +
	"\bworktree\x18\x03 \x01(\tR\bworktree\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x16\n" +
	"\x06runner\x18\x05 \x01(\tR\x06runner\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x127\n" +
	"\n" +
	"extensions\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"extensions*\x85\x01\n" +
	"\tAgentRole\x12\x1a\n" +
	"\x16AGENT_ROLE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPRODUCT_OWNER\x10\x01\x12\x13\n" +
	"\x0fPROJECT_MANAGER\x10\x02\x12\a\n" +
	"\x03DEV\x10\x03\x12\x06\n" +
	"\x02QA\x10\x04\x12\f\n" +
	"\bREVIEWER\x10\x05\x12\f\n" +
	"\bSECURITY\x10\x06\x12\a\n" +
	"\x03OPS\x10\aB\x85\x02\n" +
	"\x1bmonarchic.agent_protocol.v1B\x18MonarchicAgentProtocolV1P\x01Zdgithub.com/monarchic-ai/monarchic-agent-protocol/src/go/monarchic/agent_protocol/v1;agent_protocolv1\xa2\x02\x03MAP\xaa\x02\x1aMonarchic.AgentProtocol.V1\xca\x02\x1aMonarchic\\AgentProtocol\\V1\xe2\x02#Monarchic\\AgentProtocol\\V1\\Metadatab\x06proto3"

var (
	file_monarchic_agent_protocol_proto_rawDescOnce sync.Once
	file_monarchic_agent_protocol_proto_rawDescData []byte
)

func file_monarchic_agent_protocol_proto_rawDescGZIP() []byte {
	file_monarchic_agent_protocol_proto_rawDescOnce.Do(func() {
		file_monarchic_agent_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monarchic_agent_protocol_proto_rawDesc), len(file_monarchic_agent_protocol_proto_rawDesc)))
	})
	return file_monarchic_agent_protocol_proto_rawDescData
}

var file_monarchic_agent_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_monarchic_agent_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_monarchic_agent_protocol_proto_goTypes = []any{
	(AgentRole)(0),          // 0: monarchic.agent_protocol.v1.AgentRole
	(*Task)(nil),            // 1: monarchic.agent_protocol.v1.Task
	(*Artifact)(nil),        // 2: monarchic.agent_protocol.v1.Artifact
	(*Event)(nil),           // 3: monarchic.agent_protocol.v1.Event
	(*GateResult)(nil),      // 4: monarchic.agent_protocol.v1.GateResult
	(*RunContext)(nil),      // 5: monarchic.agent_protocol.v1.RunContext
	(*structpb.Struct)(nil), // 6: google.protobuf.Struct
}
var file_monarchic_agent_protocol_proto_depIdxs = []int32{
	0,  // 0: monarchic.agent_protocol.v1.Task.role:type_name -> monarchic.agent_protocol.v1.AgentRole
	6,  // 1: monarchic.agent_protocol.v1.Task.inputs:type_name -> google.protobuf.Struct
	6,  // 2: monarchic.agent_protocol.v1.Task.constraints:type_name -> google.protobuf.Struct
	5,  // 3: monarchic.agent_protocol.v1.Task.run_context:type_name -> monarchic.agent_protocol.v1.RunContext
	6,  // 4: monarchic.agent_protocol.v1.Task.extensions:type_name -> google.protobuf.Struct
	6,  // 5: monarchic.agent_protocol.v1.Artifact.extensions:type_name -> google.protobuf.Struct
	6,  // 6: monarchic.agent_protocol.v1.Event.extensions:type_name -> google.protobuf.Struct
	6,  // 7: monarchic.agent_protocol.v1.GateResult.evidence:type_name -> google.protobuf.Struct
	6,  // 8: monarchic.agent_protocol.v1.GateResult.extensions:type_name -> google.protobuf.Struct
	6,  // 9: monarchic.agent_protocol.v1.RunContext.extensions:type_name -> google.protobuf.Struct
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_monarchic_agent_protocol_proto_init() }
func file_monarchic_agent_protocol_proto_init() {
	if File_monarchic_agent_protocol_proto != nil {
		return
	}
	file_monarchic_agent_protocol_proto_msgTypes[2].OneofWrappers = []any{}
	file_monarchic_agent_protocol_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monarchic_agent_protocol_proto_rawDesc), len(file_monarchic_agent_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monarchic_agent_protocol_proto_goTypes,
		DependencyIndexes: file_monarchic_agent_protocol_proto_depIdxs,
		EnumInfos:         file_monarchic_agent_protocol_proto_enumTypes,
		MessageInfos:      file_monarchic_agent_protocol_proto_msgTypes,
	}.Build()
	File_monarchic_agent_protocol_proto = out.File
	file_monarchic_agent_protocol_proto_goTypes = nil
	file_monarchic_agent_protocol_proto_depIdxs = nil
}
