// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface AcceptanceCriteriaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.AcceptanceCriteria)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string metric = 1;</code>
   * @return The metric.
   */
  java.lang.String getMetric();
  /**
   * <code>string metric = 1;</code>
   * @return The bytes for metric.
   */
  com.google.protobuf.ByteString
      getMetricBytes();

  /**
   * <code>string direction = 2;</code>
   * @return The direction.
   */
  java.lang.String getDirection();
  /**
   * <code>string direction = 2;</code>
   * @return The bytes for direction.
   */
  com.google.protobuf.ByteString
      getDirectionBytes();

  /**
   * <code>double threshold = 3;</code>
   * @return The threshold.
   */
  double getThreshold();

  /**
   * <code>optional double min_effect_size = 4;</code>
   * @return Whether the minEffectSize field is set.
   */
  boolean hasMinEffectSize();
  /**
   * <code>optional double min_effect_size = 4;</code>
   * @return The minEffectSize.
   */
  double getMinEffectSize();

  /**
   * <code>optional double max_variance = 5;</code>
   * @return Whether the maxVariance field is set.
   */
  boolean hasMaxVariance();
  /**
   * <code>optional double max_variance = 5;</code>
   * @return The maxVariance.
   */
  double getMaxVariance();

  /**
   * <code>optional double confidence_level = 6;</code>
   * @return Whether the confidenceLevel field is set.
   */
  boolean hasConfidenceLevel();
  /**
   * <code>optional double confidence_level = 6;</code>
   * @return The confidenceLevel.
   */
  double getConfidenceLevel();

  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();
}
