// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf enum {@code monarchic.agent_protocol.v1.AgentRole}
 */
@com.google.protobuf.Generated
public enum AgentRole
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AGENT_ROLE_UNSPECIFIED = 0;</code>
   */
  AGENT_ROLE_UNSPECIFIED(0),
  /**
   * <code>PRODUCT_OWNER = 1;</code>
   */
  PRODUCT_OWNER(1),
  /**
   * <code>PROJECT_MANAGER = 2;</code>
   */
  PROJECT_MANAGER(2),
  /**
   * <code>DEV = 3;</code>
   */
  DEV(3),
  /**
   * <code>QA = 4;</code>
   */
  QA(4),
  /**
   * <code>REVIEWER = 5;</code>
   */
  REVIEWER(5),
  /**
   * <code>SECURITY = 6;</code>
   */
  SECURITY(6),
  /**
   * <code>OPS = 7;</code>
   */
  OPS(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      AgentRole.class.getName());
  }
  /**
   * <code>AGENT_ROLE_UNSPECIFIED = 0;</code>
   */
  public static final int AGENT_ROLE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PRODUCT_OWNER = 1;</code>
   */
  public static final int PRODUCT_OWNER_VALUE = 1;
  /**
   * <code>PROJECT_MANAGER = 2;</code>
   */
  public static final int PROJECT_MANAGER_VALUE = 2;
  /**
   * <code>DEV = 3;</code>
   */
  public static final int DEV_VALUE = 3;
  /**
   * <code>QA = 4;</code>
   */
  public static final int QA_VALUE = 4;
  /**
   * <code>REVIEWER = 5;</code>
   */
  public static final int REVIEWER_VALUE = 5;
  /**
   * <code>SECURITY = 6;</code>
   */
  public static final int SECURITY_VALUE = 6;
  /**
   * <code>OPS = 7;</code>
   */
  public static final int OPS_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AgentRole valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AgentRole forNumber(int value) {
    switch (value) {
      case 0: return AGENT_ROLE_UNSPECIFIED;
      case 1: return PRODUCT_OWNER;
      case 2: return PROJECT_MANAGER;
      case 3: return DEV;
      case 4: return QA;
      case 5: return REVIEWER;
      case 6: return SECURITY;
      case 7: return OPS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AgentRole>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AgentRole> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AgentRole>() {
          public AgentRole findValueByNumber(int number) {
            return AgentRole.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.getDescriptor().getEnumTypes().get(0);
  }

  private static final AgentRole[] VALUES = values();

  public static AgentRole valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AgentRole(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:monarchic.agent_protocol.v1.AgentRole)
}

