// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface ArtifactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.Artifact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string artifact_id = 2;</code>
   * @return The artifactId.
   */
  java.lang.String getArtifactId();
  /**
   * <code>string artifact_id = 2;</code>
   * @return The bytes for artifactId.
   */
  com.google.protobuf.ByteString
      getArtifactIdBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string summary = 4;</code>
   * @return The summary.
   */
  java.lang.String getSummary();
  /**
   * <code>string summary = 4;</code>
   * @return The bytes for summary.
   */
  com.google.protobuf.ByteString
      getSummaryBytes();

  /**
   * <code>string path = 5;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 5;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string task_id = 6;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 6;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();

  /**
   * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
   * @return Whether the provenance field is set.
   */
  boolean hasProvenance();
  /**
   * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
   * @return The provenance.
   */
  ai.monarchic.agent_protocol.v1.Provenance getProvenance();
  /**
   * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
   */
  ai.monarchic.agent_protocol.v1.ProvenanceOrBuilder getProvenanceOrBuilder();

  /**
   * <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
   */
  java.util.List<ai.monarchic.agent_protocol.v1.DatasetRef> 
      getDatasetRefsList();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
   */
  ai.monarchic.agent_protocol.v1.DatasetRef getDatasetRefs(int index);
  /**
   * <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
   */
  int getDatasetRefsCount();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
   */
  java.util.List<? extends ai.monarchic.agent_protocol.v1.DatasetRefOrBuilder> 
      getDatasetRefsOrBuilderList();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
   */
  ai.monarchic.agent_protocol.v1.DatasetRefOrBuilder getDatasetRefsOrBuilder(
      int index);

  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
   */
  java.util.List<ai.monarchic.agent_protocol.v1.EvalResult> 
      getEvalResultsList();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
   */
  ai.monarchic.agent_protocol.v1.EvalResult getEvalResults(int index);
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
   */
  int getEvalResultsCount();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
   */
  java.util.List<? extends ai.monarchic.agent_protocol.v1.EvalResultOrBuilder> 
      getEvalResultsOrBuilderList();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
   */
  ai.monarchic.agent_protocol.v1.EvalResultOrBuilder getEvalResultsOrBuilder(
      int index);

  /**
   * <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 11;</code>
   * @return Whether the experimentSpec field is set.
   */
  boolean hasExperimentSpec();
  /**
   * <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 11;</code>
   * @return The experimentSpec.
   */
  ai.monarchic.agent_protocol.v1.ExperimentSpec getExperimentSpec();
  /**
   * <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 11;</code>
   */
  ai.monarchic.agent_protocol.v1.ExperimentSpecOrBuilder getExperimentSpecOrBuilder();
}
