// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface DatasetRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.DatasetRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataset_id = 1;</code>
   * @return The datasetId.
   */
  java.lang.String getDatasetId();
  /**
   * <code>string dataset_id = 1;</code>
   * @return The bytes for datasetId.
   */
  com.google.protobuf.ByteString
      getDatasetIdBytes();

  /**
   * <code>optional string uri = 2;</code>
   * @return Whether the uri field is set.
   */
  boolean hasUri();
  /**
   * <code>optional string uri = 2;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <code>optional string uri = 2;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <code>string sha256 = 3;</code>
   * @return The sha256.
   */
  java.lang.String getSha256();
  /**
   * <code>string sha256 = 3;</code>
   * @return The bytes for sha256.
   */
  com.google.protobuf.ByteString
      getSha256Bytes();

  /**
   * <code>string format = 4;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 4;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>optional string split = 5;</code>
   * @return Whether the split field is set.
   */
  boolean hasSplit();
  /**
   * <code>optional string split = 5;</code>
   * @return The split.
   */
  java.lang.String getSplit();
  /**
   * <code>optional string split = 5;</code>
   * @return The bytes for split.
   */
  com.google.protobuf.ByteString
      getSplitBytes();

  /**
   * <code>optional uint64 size_bytes = 6;</code>
   * @return Whether the sizeBytes field is set.
   */
  boolean hasSizeBytes();
  /**
   * <code>optional uint64 size_bytes = 6;</code>
   * @return The sizeBytes.
   */
  long getSizeBytes();

  /**
   * <code>optional string description = 7;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 7;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 7;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.Struct extensions = 8;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 8;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 8;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();
}
