// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf type {@code monarchic.agent_protocol.v1.Event}
 */
@com.google.protobuf.Generated
public final class Event extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:monarchic.agent_protocol.v1.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      Event.class.getName());
  }
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    version_ = "";
    eventType_ = "";
    timestamp_ = "";
    taskId_ = "";
    status_ = "";
    message_ = "";
    evalResults_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Event_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.monarchic.agent_protocol.v1.Event.class, ai.monarchic.agent_protocol.v1.Event.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventType_ = "";
  /**
   * <code>string event_type = 2;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <code>string event_type = 2;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timestamp_ = "";
  /**
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskId_ = "";
  /**
   * <code>string task_id = 4;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_id = 4;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>optional string message = 6;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string message = 6;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>optional string message = 6;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 7;
  private com.google.protobuf.Struct extensions_;
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return Whether the extensions field is set.
   */
  @java.lang.Override
  public boolean hasExtensions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return The extensions.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getExtensions() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }

  public static final int PROVENANCE_FIELD_NUMBER = 8;
  private ai.monarchic.agent_protocol.v1.Provenance provenance_;
  /**
   * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
   * @return Whether the provenance field is set.
   */
  @java.lang.Override
  public boolean hasProvenance() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
   * @return The provenance.
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.Provenance getProvenance() {
    return provenance_ == null ? ai.monarchic.agent_protocol.v1.Provenance.getDefaultInstance() : provenance_;
  }
  /**
   * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.ProvenanceOrBuilder getProvenanceOrBuilder() {
    return provenance_ == null ? ai.monarchic.agent_protocol.v1.Provenance.getDefaultInstance() : provenance_;
  }

  public static final int EVAL_RESULTS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<ai.monarchic.agent_protocol.v1.EvalResult> evalResults_;
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
   */
  @java.lang.Override
  public java.util.List<ai.monarchic.agent_protocol.v1.EvalResult> getEvalResultsList() {
    return evalResults_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.monarchic.agent_protocol.v1.EvalResultOrBuilder> 
      getEvalResultsOrBuilderList() {
    return evalResults_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
   */
  @java.lang.Override
  public int getEvalResultsCount() {
    return evalResults_.size();
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.EvalResult getEvalResults(int index) {
    return evalResults_.get(index);
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.EvalResultOrBuilder getEvalResultsOrBuilder(
      int index) {
    return evalResults_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, version_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timestamp_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, taskId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, message_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getExtensions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(8, getProvenance());
    }
    for (int i = 0; i < evalResults_.size(); i++) {
      output.writeMessage(9, evalResults_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, version_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timestamp_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, taskId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, message_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getExtensions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getProvenance());
    }
    for (int i = 0; i < evalResults_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, evalResults_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.monarchic.agent_protocol.v1.Event)) {
      return super.equals(obj);
    }
    ai.monarchic.agent_protocol.v1.Event other = (ai.monarchic.agent_protocol.v1.Event) obj;

    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (hasExtensions() != other.hasExtensions()) return false;
    if (hasExtensions()) {
      if (!getExtensions()
          .equals(other.getExtensions())) return false;
    }
    if (hasProvenance() != other.hasProvenance()) return false;
    if (hasProvenance()) {
      if (!getProvenance()
          .equals(other.getProvenance())) return false;
    }
    if (!getEvalResultsList()
        .equals(other.getEvalResultsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (hasExtensions()) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensions().hashCode();
    }
    if (hasProvenance()) {
      hash = (37 * hash) + PROVENANCE_FIELD_NUMBER;
      hash = (53 * hash) + getProvenance().hashCode();
    }
    if (getEvalResultsCount() > 0) {
      hash = (37 * hash) + EVAL_RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getEvalResultsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.monarchic.agent_protocol.v1.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.monarchic.agent_protocol.v1.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.monarchic.agent_protocol.v1.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code monarchic.agent_protocol.v1.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:monarchic.agent_protocol.v1.Event)
      ai.monarchic.agent_protocol.v1.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.monarchic.agent_protocol.v1.Event.class, ai.monarchic.agent_protocol.v1.Event.Builder.class);
    }

    // Construct using ai.monarchic.agent_protocol.v1.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetExtensionsFieldBuilder();
        internalGetProvenanceFieldBuilder();
        internalGetEvalResultsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = "";
      eventType_ = "";
      timestamp_ = "";
      taskId_ = "";
      status_ = "";
      message_ = "";
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      provenance_ = null;
      if (provenanceBuilder_ != null) {
        provenanceBuilder_.dispose();
        provenanceBuilder_ = null;
      }
      if (evalResultsBuilder_ == null) {
        evalResults_ = java.util.Collections.emptyList();
      } else {
        evalResults_ = null;
        evalResultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Event_descriptor;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.Event getDefaultInstanceForType() {
      return ai.monarchic.agent_protocol.v1.Event.getDefaultInstance();
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.Event build() {
      ai.monarchic.agent_protocol.v1.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.Event buildPartial() {
      ai.monarchic.agent_protocol.v1.Event result = new ai.monarchic.agent_protocol.v1.Event(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.monarchic.agent_protocol.v1.Event result) {
      if (evalResultsBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          evalResults_ = java.util.Collections.unmodifiableList(evalResults_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.evalResults_ = evalResults_;
      } else {
        result.evalResults_ = evalResultsBuilder_.build();
      }
    }

    private void buildPartial0(ai.monarchic.agent_protocol.v1.Event result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.eventType_ = eventType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.taskId_ = taskId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.message_ = message_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.extensions_ = extensionsBuilder_ == null
            ? extensions_
            : extensionsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.provenance_ = provenanceBuilder_ == null
            ? provenance_
            : provenanceBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.monarchic.agent_protocol.v1.Event) {
        return mergeFrom((ai.monarchic.agent_protocol.v1.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.monarchic.agent_protocol.v1.Event other) {
      if (other == ai.monarchic.agent_protocol.v1.Event.getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasMessage()) {
        message_ = other.message_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasExtensions()) {
        mergeExtensions(other.getExtensions());
      }
      if (other.hasProvenance()) {
        mergeProvenance(other.getProvenance());
      }
      if (evalResultsBuilder_ == null) {
        if (!other.evalResults_.isEmpty()) {
          if (evalResults_.isEmpty()) {
            evalResults_ = other.evalResults_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureEvalResultsIsMutable();
            evalResults_.addAll(other.evalResults_);
          }
          onChanged();
        }
      } else {
        if (!other.evalResults_.isEmpty()) {
          if (evalResultsBuilder_.isEmpty()) {
            evalResultsBuilder_.dispose();
            evalResultsBuilder_ = null;
            evalResults_ = other.evalResults_;
            bitField0_ = (bitField0_ & ~0x00000100);
            evalResultsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetEvalResultsFieldBuilder() : null;
          } else {
            evalResultsBuilder_.addAllMessages(other.evalResults_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              timestamp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetExtensionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetProvenanceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              ai.monarchic.agent_protocol.v1.EvalResult m =
                  input.readMessage(
                      ai.monarchic.agent_protocol.v1.EvalResult.parser(),
                      extensionRegistry);
              if (evalResultsBuilder_ == null) {
                ensureEvalResultsIsMutable();
                evalResults_.add(m);
              } else {
                evalResultsBuilder_.addMessage(m);
              }
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <code>string event_type = 2;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_type = 2;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_type = 2;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string event_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string event_type = 2;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 3;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      timestamp_ = getDefaultInstance().getTimestamp();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 3;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <code>string task_id = 4;</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_id = 4;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_id = 4;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 4;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 5;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 6;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string message = 6;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 6;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 6;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 6;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct extensions_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> extensionsBuilder_;
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     * @return Whether the extensions field is set.
     */
    public boolean hasExtensions() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     * @return The extensions.
     */
    public com.google.protobuf.Struct getExtensions() {
      if (extensionsBuilder_ == null) {
        return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      } else {
        return extensionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     */
    public Builder setExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        extensions_ = value;
      } else {
        extensionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     */
    public Builder setExtensions(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        extensions_ = builderForValue.build();
      } else {
        extensionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     */
    public Builder mergeExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          extensions_ != null &&
          extensions_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getExtensionsBuilder().mergeFrom(value);
        } else {
          extensions_ = value;
        }
      } else {
        extensionsBuilder_.mergeFrom(value);
      }
      if (extensions_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     */
    public Builder clearExtensions() {
      bitField0_ = (bitField0_ & ~0x00000040);
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     */
    public com.google.protobuf.Struct.Builder getExtensionsBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetExtensionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     */
    public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
      if (extensionsBuilder_ != null) {
        return extensionsBuilder_.getMessageOrBuilder();
      } else {
        return extensions_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        internalGetExtensionsFieldBuilder() {
      if (extensionsBuilder_ == null) {
        extensionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getExtensions(),
                getParentForChildren(),
                isClean());
        extensions_ = null;
      }
      return extensionsBuilder_;
    }

    private ai.monarchic.agent_protocol.v1.Provenance provenance_;
    private com.google.protobuf.SingleFieldBuilder<
        ai.monarchic.agent_protocol.v1.Provenance, ai.monarchic.agent_protocol.v1.Provenance.Builder, ai.monarchic.agent_protocol.v1.ProvenanceOrBuilder> provenanceBuilder_;
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     * @return Whether the provenance field is set.
     */
    public boolean hasProvenance() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     * @return The provenance.
     */
    public ai.monarchic.agent_protocol.v1.Provenance getProvenance() {
      if (provenanceBuilder_ == null) {
        return provenance_ == null ? ai.monarchic.agent_protocol.v1.Provenance.getDefaultInstance() : provenance_;
      } else {
        return provenanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    public Builder setProvenance(ai.monarchic.agent_protocol.v1.Provenance value) {
      if (provenanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        provenance_ = value;
      } else {
        provenanceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    public Builder setProvenance(
        ai.monarchic.agent_protocol.v1.Provenance.Builder builderForValue) {
      if (provenanceBuilder_ == null) {
        provenance_ = builderForValue.build();
      } else {
        provenanceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    public Builder mergeProvenance(ai.monarchic.agent_protocol.v1.Provenance value) {
      if (provenanceBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          provenance_ != null &&
          provenance_ != ai.monarchic.agent_protocol.v1.Provenance.getDefaultInstance()) {
          getProvenanceBuilder().mergeFrom(value);
        } else {
          provenance_ = value;
        }
      } else {
        provenanceBuilder_.mergeFrom(value);
      }
      if (provenance_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    public Builder clearProvenance() {
      bitField0_ = (bitField0_ & ~0x00000080);
      provenance_ = null;
      if (provenanceBuilder_ != null) {
        provenanceBuilder_.dispose();
        provenanceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.Provenance.Builder getProvenanceBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetProvenanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.ProvenanceOrBuilder getProvenanceOrBuilder() {
      if (provenanceBuilder_ != null) {
        return provenanceBuilder_.getMessageOrBuilder();
      } else {
        return provenance_ == null ?
            ai.monarchic.agent_protocol.v1.Provenance.getDefaultInstance() : provenance_;
      }
    }
    /**
     * <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.monarchic.agent_protocol.v1.Provenance, ai.monarchic.agent_protocol.v1.Provenance.Builder, ai.monarchic.agent_protocol.v1.ProvenanceOrBuilder> 
        internalGetProvenanceFieldBuilder() {
      if (provenanceBuilder_ == null) {
        provenanceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.monarchic.agent_protocol.v1.Provenance, ai.monarchic.agent_protocol.v1.Provenance.Builder, ai.monarchic.agent_protocol.v1.ProvenanceOrBuilder>(
                getProvenance(),
                getParentForChildren(),
                isClean());
        provenance_ = null;
      }
      return provenanceBuilder_;
    }

    private java.util.List<ai.monarchic.agent_protocol.v1.EvalResult> evalResults_ =
      java.util.Collections.emptyList();
    private void ensureEvalResultsIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        evalResults_ = new java.util.ArrayList<ai.monarchic.agent_protocol.v1.EvalResult>(evalResults_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.EvalResult, ai.monarchic.agent_protocol.v1.EvalResult.Builder, ai.monarchic.agent_protocol.v1.EvalResultOrBuilder> evalResultsBuilder_;

    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.EvalResult> getEvalResultsList() {
      if (evalResultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(evalResults_);
      } else {
        return evalResultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public int getEvalResultsCount() {
      if (evalResultsBuilder_ == null) {
        return evalResults_.size();
      } else {
        return evalResultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.EvalResult getEvalResults(int index) {
      if (evalResultsBuilder_ == null) {
        return evalResults_.get(index);
      } else {
        return evalResultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder setEvalResults(
        int index, ai.monarchic.agent_protocol.v1.EvalResult value) {
      if (evalResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvalResultsIsMutable();
        evalResults_.set(index, value);
        onChanged();
      } else {
        evalResultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder setEvalResults(
        int index, ai.monarchic.agent_protocol.v1.EvalResult.Builder builderForValue) {
      if (evalResultsBuilder_ == null) {
        ensureEvalResultsIsMutable();
        evalResults_.set(index, builderForValue.build());
        onChanged();
      } else {
        evalResultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder addEvalResults(ai.monarchic.agent_protocol.v1.EvalResult value) {
      if (evalResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvalResultsIsMutable();
        evalResults_.add(value);
        onChanged();
      } else {
        evalResultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder addEvalResults(
        int index, ai.monarchic.agent_protocol.v1.EvalResult value) {
      if (evalResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvalResultsIsMutable();
        evalResults_.add(index, value);
        onChanged();
      } else {
        evalResultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder addEvalResults(
        ai.monarchic.agent_protocol.v1.EvalResult.Builder builderForValue) {
      if (evalResultsBuilder_ == null) {
        ensureEvalResultsIsMutable();
        evalResults_.add(builderForValue.build());
        onChanged();
      } else {
        evalResultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder addEvalResults(
        int index, ai.monarchic.agent_protocol.v1.EvalResult.Builder builderForValue) {
      if (evalResultsBuilder_ == null) {
        ensureEvalResultsIsMutable();
        evalResults_.add(index, builderForValue.build());
        onChanged();
      } else {
        evalResultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder addAllEvalResults(
        java.lang.Iterable<? extends ai.monarchic.agent_protocol.v1.EvalResult> values) {
      if (evalResultsBuilder_ == null) {
        ensureEvalResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, evalResults_);
        onChanged();
      } else {
        evalResultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder clearEvalResults() {
      if (evalResultsBuilder_ == null) {
        evalResults_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        evalResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public Builder removeEvalResults(int index) {
      if (evalResultsBuilder_ == null) {
        ensureEvalResultsIsMutable();
        evalResults_.remove(index);
        onChanged();
      } else {
        evalResultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.EvalResult.Builder getEvalResultsBuilder(
        int index) {
      return internalGetEvalResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.EvalResultOrBuilder getEvalResultsOrBuilder(
        int index) {
      if (evalResultsBuilder_ == null) {
        return evalResults_.get(index);  } else {
        return evalResultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public java.util.List<? extends ai.monarchic.agent_protocol.v1.EvalResultOrBuilder> 
         getEvalResultsOrBuilderList() {
      if (evalResultsBuilder_ != null) {
        return evalResultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(evalResults_);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.EvalResult.Builder addEvalResultsBuilder() {
      return internalGetEvalResultsFieldBuilder().addBuilder(
          ai.monarchic.agent_protocol.v1.EvalResult.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.EvalResult.Builder addEvalResultsBuilder(
        int index) {
      return internalGetEvalResultsFieldBuilder().addBuilder(
          index, ai.monarchic.agent_protocol.v1.EvalResult.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.EvalResult.Builder> 
         getEvalResultsBuilderList() {
      return internalGetEvalResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.EvalResult, ai.monarchic.agent_protocol.v1.EvalResult.Builder, ai.monarchic.agent_protocol.v1.EvalResultOrBuilder> 
        internalGetEvalResultsFieldBuilder() {
      if (evalResultsBuilder_ == null) {
        evalResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ai.monarchic.agent_protocol.v1.EvalResult, ai.monarchic.agent_protocol.v1.EvalResult.Builder, ai.monarchic.agent_protocol.v1.EvalResultOrBuilder>(
                evalResults_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        evalResults_ = null;
      }
      return evalResultsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:monarchic.agent_protocol.v1.Event)
  }

  // @@protoc_insertion_point(class_scope:monarchic.agent_protocol.v1.Event)
  private static final ai.monarchic.agent_protocol.v1.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.monarchic.agent_protocol.v1.Event();
  }

  public static ai.monarchic.agent_protocol.v1.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

