// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monarchic_agent_protocol.proto

package ai.monarchic.agent_protocol.v1;

public interface GateResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.GateResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string gate = 2;</code>
   * @return The gate.
   */
  java.lang.String getGate();
  /**
   * <code>string gate = 2;</code>
   * @return The bytes for gate.
   */
  com.google.protobuf.ByteString
      getGateBytes();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>optional string reason = 4;</code>
   * @return Whether the reason field is set.
   */
  boolean hasReason();
  /**
   * <code>optional string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>optional string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>.google.protobuf.Struct evidence = 5;</code>
   * @return Whether the evidence field is set.
   */
  boolean hasEvidence();
  /**
   * <code>.google.protobuf.Struct evidence = 5;</code>
   * @return The evidence.
   */
  com.google.protobuf.Struct getEvidence();
  /**
   * <code>.google.protobuf.Struct evidence = 5;</code>
   */
  com.google.protobuf.StructOrBuilder getEvidenceOrBuilder();

  /**
   * <code>.google.protobuf.Struct extensions = 6;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 6;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 6;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();
}
