// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public final class MonarchicAgentProtocolV1 extends com.google.protobuf.GeneratedFile {
  private MonarchicAgentProtocolV1() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      MonarchicAgentProtocolV1.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_DatasetRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_DatasetRef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ExperimentSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ExperimentSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_DeliveryContract_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_DeliveryContract_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_EvalResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_EvalResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Provenance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Provenance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Artifact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Artifact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_GateResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_GateResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RunContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RunContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036monarchic_agent_protocol.proto\022\033monarc" +
      "hic.agent_protocol.v1\032\034google/protobuf/s" +
      "truct.proto\"\367\001\n\nDatasetRef\022\022\n\ndataset_id" +
      "\030\001 \001(\t\022\020\n\003uri\030\002 \001(\tH\000\210\001\001\022\016\n\006sha256\030\003 \001(\t" +
      "\022\016\n\006format\030\004 \001(\t\022\022\n\005split\030\005 \001(\tH\001\210\001\001\022\027\n\n" +
      "size_bytes\030\006 \001(\004H\002\210\001\001\022\030\n\013description\030\007 \001" +
      "(\tH\003\210\001\001\022+\n\nextensions\030\010 \001(\0132\027.google.pro" +
      "tobuf.StructB\006\n\004_uriB\010\n\006_splitB\r\n\013_size_" +
      "bytesB\016\n\014_description\"\211\002\n\022AcceptanceCrit" +
      "eria\022\016\n\006metric\030\001 \001(\t\022\021\n\tdirection\030\002 \001(\t\022" +
      "\021\n\tthreshold\030\003 \001(\001\022\034\n\017min_effect_size\030\004 " +
      "\001(\001H\000\210\001\001\022\031\n\014max_variance\030\005 \001(\001H\001\210\001\001\022\035\n\020c" +
      "onfidence_level\030\006 \001(\001H\002\210\001\001\022+\n\nextensions" +
      "\030\007 \001(\0132\027.google.protobuf.StructB\022\n\020_min_" +
      "effect_sizeB\017\n\r_max_varianceB\023\n\021_confide" +
      "nce_level\"\374\002\n\016ExperimentSpec\022\025\n\rexperime" +
      "nt_id\030\001 \001(\t\022\021\n\tobjective\030\002 \001(\t\022\027\n\nhypoth" +
      "esis\030\003 \001(\tH\000\210\001\001\022\031\n\014model_family\030\004 \001(\tH\001\210" +
      "\001\001\022\r\n\005seeds\030\005 \003(\003\022=\n\014dataset_refs\030\006 \003(\0132" +
      "\'.monarchic.agent_protocol.v1.DatasetRef" +
      "\022C\n\nacceptance\030\007 \001(\0132/.monarchic.agent_p" +
      "rotocol.v1.AcceptanceCriteria\022,\n\013constra" +
      "ints\030\010 \001(\0132\027.google.protobuf.Struct\022+\n\ne" +
      "xtensions\030\t \001(\0132\027.google.protobuf.Struct" +
      "B\r\n\013_hypothesisB\017\n\r_model_family\"\256\003\n\020Del" +
      "iveryContract\022\021\n\tobjective\030\001 \001(\t\022\032\n\022defi" +
      "nition_of_done\030\002 \003(\t\022\027\n\017required_checks\030" +
      "\003 \003(\t\022\021\n\trisk_tier\030\004 \001(\t\022\036\n\021max_cycle_mi" +
      "nutes\030\005 \001(\rH\000\210\001\001\022\034\n\017max_agent_turns\030\006 \001(" +
      "\rH\001\210\001\001\022\030\n\013pr_strategy\030\007 \001(\tH\002\210\001\001\022\032\n\rrevi" +
      "ew_policy\030\010 \001(\tH\003\210\001\001\022\036\n\021rollback_strateg" +
      "y\030\t \001(\tH\004\210\001\001\022\022\n\005notes\030\n \001(\tH\005\210\001\001\022+\n\nexte" +
      "nsions\030\013 \001(\0132\027.google.protobuf.StructB\024\n" +
      "\022_max_cycle_minutesB\022\n\020_max_agent_turnsB" +
      "\016\n\014_pr_strategyB\020\n\016_review_policyB\024\n\022_ro" +
      "llback_strategyB\010\n\006_notes\"\363\002\n\rObjectiveS" +
      "pec\022\022\n\nmetric_key\030\001 \001(\t\022\021\n\tdirection\030\002 \001" +
      "(\t\022\023\n\006target\030\003 \001(\001H\000\210\001\001\022\026\n\tmin_delta\030\004 \001" +
      "(\001H\001\210\001\001\022\026\n\ttolerance\030\005 \001(\001H\002\210\001\001\022\030\n\013repor" +
      "t_file\030\006 \001(\tH\003\210\001\001\022\033\n\016report_task_id\030\007 \001(" +
      "\tH\004\210\001\001\022\023\n\006weight\030\010 \001(\001H\005\210\001\001\022\030\n\013descripti" +
      "on\030\t \001(\tH\006\210\001\001\022+\n\nextensions\030\n \001(\0132\027.goog" +
      "le.protobuf.StructB\t\n\007_targetB\014\n\n_min_de" +
      "ltaB\014\n\n_toleranceB\016\n\014_report_fileB\021\n\017_re" +
      "port_task_idB\t\n\007_weightB\016\n\014_description\"" +
      "\216\002\n\nEvalResult\022\016\n\006metric\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\001\022\025\n\010lower_ci\030\003 \001(\001H\000\210\001\001\022\025\n\010upper_ci" +
      "\030\004 \001(\001H\001\210\001\001\022\025\n\010variance\030\005 \001(\001H\002\210\001\001\022\021\n\004se" +
      "ed\030\006 \001(\003H\003\210\001\001\022\016\n\006passed\030\007 \001(\010\022\022\n\005notes\030\010" +
      " \001(\tH\004\210\001\001\022+\n\nextensions\030\t \001(\0132\027.google.p" +
      "rotobuf.StructB\013\n\t_lower_ciB\013\n\t_upper_ci" +
      "B\013\n\t_varianceB\007\n\005_seedB\010\n\006_notes\"\353\003\n\nPro" +
      "venance\022\025\n\rprompt_sha256\030\001 \001(\t\022\023\n\013code_s" +
      "ha256\030\002 \001(\t\022\026\n\016dataset_sha256\030\003 \003(\t\022\017\n\007r" +
      "untime\030\004 \001(\t\022\022\n\005model\030\005 \001(\tH\000\210\001\001\022\016\n\006runn" +
      "er\030\006 \001(\t\022\024\n\014orchestrator\030\007 \001(\t\022\035\n\020task_s" +
      "pec_sha256\030\010 \001(\tH\001\210\001\001\022\034\n\017pipeline_sha256" +
      "\030\t \001(\tH\002\210\001\001\022\033\n\016command_sha256\030\n \001(\tH\003\210\001\001" +
      "\022\022\n\ncreated_at\030\013 \001(\t\022\033\n\016source_task_id\030\014" +
      " \001(\tH\004\210\001\001\022=\n\014dataset_refs\030\r \003(\0132\'.monarc" +
      "hic.agent_protocol.v1.DatasetRef\022+\n\nexte" +
      "nsions\030\016 \001(\0132\027.google.protobuf.StructB\010\n" +
      "\006_modelB\023\n\021_task_spec_sha256B\022\n\020_pipelin" +
      "e_sha256B\021\n\017_command_sha256B\021\n\017_source_t" +
      "ask_id\"\232\004\n\004Task\022\017\n\007version\030\001 \001(\t\022\017\n\007task" +
      "_id\030\002 \001(\t\0224\n\004role\030\003 \001(\0162&.monarchic.agen" +
      "t_protocol.v1.AgentRole\022\014\n\004goal\030\004 \001(\t\022\'\n" +
      "\006inputs\030\005 \001(\0132\027.google.protobuf.Struct\022," +
      "\n\013constraints\030\006 \001(\0132\027.google.protobuf.St" +
      "ruct\022\026\n\016gates_required\030\007 \003(\t\022<\n\013run_cont" +
      "ext\030\010 \001(\0132\'.monarchic.agent_protocol.v1." +
      "RunContext\022+\n\nextensions\030\t \001(\0132\027.google." +
      "protobuf.Struct\022D\n\017experiment_spec\030\n \001(\013" +
      "2+.monarchic.agent_protocol.v1.Experimen" +
      "tSpec\022H\n\021delivery_contract\030\013 \001(\0132-.monar" +
      "chic.agent_protocol.v1.DeliveryContract\022" +
      "B\n\016objective_spec\030\014 \001(\0132*.monarchic.agen" +
      "t_protocol.v1.ObjectiveSpec\"\234\003\n\010Artifact" +
      "\022\017\n\007version\030\001 \001(\t\022\023\n\013artifact_id\030\002 \001(\t\022\014" +
      "\n\004type\030\003 \001(\t\022\017\n\007summary\030\004 \001(\t\022\014\n\004path\030\005 " +
      "\001(\t\022\017\n\007task_id\030\006 \001(\t\022+\n\nextensions\030\007 \001(\013" +
      "2\027.google.protobuf.Struct\022;\n\nprovenance\030" +
      "\010 \001(\0132\'.monarchic.agent_protocol.v1.Prov" +
      "enance\022=\n\014dataset_refs\030\t \003(\0132\'.monarchic" +
      ".agent_protocol.v1.DatasetRef\022=\n\014eval_re" +
      "sults\030\n \003(\0132\'.monarchic.agent_protocol.v" +
      "1.EvalResult\022D\n\017experiment_spec\030\013 \001(\0132+." +
      "monarchic.agent_protocol.v1.ExperimentSp" +
      "ec\"\253\002\n\005Event\022\017\n\007version\030\001 \001(\t\022\022\n\nevent_t" +
      "ype\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t\022\017\n\007task_id\030" +
      "\004 \001(\t\022\016\n\006status\030\005 \001(\t\022\024\n\007message\030\006 \001(\tH\000" +
      "\210\001\001\022+\n\nextensions\030\007 \001(\0132\027.google.protobu" +
      "f.Struct\022;\n\nprovenance\030\010 \001(\0132\'.monarchic" +
      ".agent_protocol.v1.Provenance\022=\n\014eval_re" +
      "sults\030\t \003(\0132\'.monarchic.agent_protocol.v" +
      "1.EvalResultB\n\n\010_message\"\263\001\n\nGateResult\022" +
      "\017\n\007version\030\001 \001(\t\022\014\n\004gate\030\002 \001(\t\022\016\n\006status" +
      "\030\003 \001(\t\022\023\n\006reason\030\004 \001(\tH\000\210\001\001\022)\n\010evidence\030" +
      "\005 \001(\0132\027.google.protobuf.Struct\022+\n\nextens" +
      "ions\030\006 \001(\0132\027.google.protobuf.StructB\t\n\007_" +
      "reason\"\231\001\n\nRunContext\022\017\n\007version\030\001 \001(\t\022\014" +
      "\n\004repo\030\002 \001(\t\022\020\n\010worktree\030\003 \001(\t\022\r\n\005image\030" +
      "\004 \001(\t\022\016\n\006runner\030\005 \001(\t\022\016\n\006labels\030\006 \003(\t\022+\n" +
      "\nextensions\030\007 \001(\0132\027.google.protobuf.Stru" +
      "ct*\205\001\n\tAgentRole\022\032\n\026AGENT_ROLE_UNSPECIFI" +
      "ED\020\000\022\021\n\rPRODUCT_OWNER\020\001\022\023\n\017PROJECT_MANAG" +
      "ER\020\002\022\007\n\003DEV\020\003\022\006\n\002QA\020\004\022\014\n\010REVIEWER\020\005\022\014\n\010S" +
      "ECURITY\020\006\022\007\n\003OPS\020\007B\210\002\n\036ai.monarchic.agen" +
      "t_protocol.v1B\030MonarchicAgentProtocolV1P" +
      "\001Zdgithub.com/monarchic-ai/monarchic-age" +
      "nt-protocol/src/go/monarchic/agent_proto" +
      "col/v1;agent_protocolv1\242\002\003MAP\252\002\032Monarchi" +
      "c.AgentProtocol.V1\312\002\032Monarchic\\AgentProt" +
      "ocol\\V1\342\002#Monarchic\\AgentProtocol\\V1\\Met" +
      "adatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_monarchic_agent_protocol_v1_DatasetRef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_monarchic_agent_protocol_v1_DatasetRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_DatasetRef_descriptor,
        new java.lang.String[] { "DatasetId", "Uri", "Sha256", "Format", "Split", "SizeBytes", "Description", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_descriptor,
        new java.lang.String[] { "Metric", "Direction", "Threshold", "MinEffectSize", "MaxVariance", "ConfidenceLevel", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ExperimentSpec_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_monarchic_agent_protocol_v1_ExperimentSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ExperimentSpec_descriptor,
        new java.lang.String[] { "ExperimentId", "Objective", "Hypothesis", "ModelFamily", "Seeds", "DatasetRefs", "Acceptance", "Constraints", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_DeliveryContract_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_monarchic_agent_protocol_v1_DeliveryContract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_DeliveryContract_descriptor,
        new java.lang.String[] { "Objective", "DefinitionOfDone", "RequiredChecks", "RiskTier", "MaxCycleMinutes", "MaxAgentTurns", "PrStrategy", "ReviewPolicy", "RollbackStrategy", "Notes", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor,
        new java.lang.String[] { "MetricKey", "Direction", "Target", "MinDelta", "Tolerance", "ReportFile", "ReportTaskId", "Weight", "Description", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_EvalResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_monarchic_agent_protocol_v1_EvalResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_EvalResult_descriptor,
        new java.lang.String[] { "Metric", "Value", "LowerCi", "UpperCi", "Variance", "Seed", "Passed", "Notes", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_Provenance_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_monarchic_agent_protocol_v1_Provenance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Provenance_descriptor,
        new java.lang.String[] { "PromptSha256", "CodeSha256", "DatasetSha256", "Runtime", "Model", "Runner", "Orchestrator", "TaskSpecSha256", "PipelineSha256", "CommandSha256", "CreatedAt", "SourceTaskId", "DatasetRefs", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_Task_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_monarchic_agent_protocol_v1_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Task_descriptor,
        new java.lang.String[] { "Version", "TaskId", "Role", "Goal", "Inputs", "Constraints", "GatesRequired", "RunContext", "Extensions", "ExperimentSpec", "DeliveryContract", "ObjectiveSpec", });
    internal_static_monarchic_agent_protocol_v1_Artifact_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_monarchic_agent_protocol_v1_Artifact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Artifact_descriptor,
        new java.lang.String[] { "Version", "ArtifactId", "Type", "Summary", "Path", "TaskId", "Extensions", "Provenance", "DatasetRefs", "EvalResults", "ExperimentSpec", });
    internal_static_monarchic_agent_protocol_v1_Event_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_monarchic_agent_protocol_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Event_descriptor,
        new java.lang.String[] { "Version", "EventType", "Timestamp", "TaskId", "Status", "Message", "Extensions", "Provenance", "EvalResults", });
    internal_static_monarchic_agent_protocol_v1_GateResult_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_monarchic_agent_protocol_v1_GateResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_GateResult_descriptor,
        new java.lang.String[] { "Version", "Gate", "Status", "Reason", "Evidence", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RunContext_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_monarchic_agent_protocol_v1_RunContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RunContext_descriptor,
        new java.lang.String[] { "Version", "Repo", "Worktree", "Image", "Runner", "Labels", "Extensions", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
