// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf type {@code monarchic.agent_protocol.v1.ObjectiveSpec}
 */
@com.google.protobuf.Generated
public final class ObjectiveSpec extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:monarchic.agent_protocol.v1.ObjectiveSpec)
    ObjectiveSpecOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      ObjectiveSpec.class.getName());
  }
  // Use ObjectiveSpec.newBuilder() to construct.
  private ObjectiveSpec(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ObjectiveSpec() {
    metricKey_ = "";
    direction_ = "";
    reportFile_ = "";
    reportTaskId_ = "";
    description_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.monarchic.agent_protocol.v1.ObjectiveSpec.class, ai.monarchic.agent_protocol.v1.ObjectiveSpec.Builder.class);
  }

  private int bitField0_;
  public static final int METRIC_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object metricKey_ = "";
  /**
   * <code>string metric_key = 1;</code>
   * @return The metricKey.
   */
  @java.lang.Override
  public java.lang.String getMetricKey() {
    java.lang.Object ref = metricKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metricKey_ = s;
      return s;
    }
  }
  /**
   * <code>string metric_key = 1;</code>
   * @return The bytes for metricKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetricKeyBytes() {
    java.lang.Object ref = metricKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metricKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object direction_ = "";
  /**
   * <code>string direction = 2;</code>
   * @return The direction.
   */
  @java.lang.Override
  public java.lang.String getDirection() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      direction_ = s;
      return s;
    }
  }
  /**
   * <code>string direction = 2;</code>
   * @return The bytes for direction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDirectionBytes() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      direction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_FIELD_NUMBER = 3;
  private double target_ = 0D;
  /**
   * <code>optional double target = 3;</code>
   * @return Whether the target field is set.
   */
  @java.lang.Override
  public boolean hasTarget() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional double target = 3;</code>
   * @return The target.
   */
  @java.lang.Override
  public double getTarget() {
    return target_;
  }

  public static final int MIN_DELTA_FIELD_NUMBER = 4;
  private double minDelta_ = 0D;
  /**
   * <code>optional double min_delta = 4;</code>
   * @return Whether the minDelta field is set.
   */
  @java.lang.Override
  public boolean hasMinDelta() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional double min_delta = 4;</code>
   * @return The minDelta.
   */
  @java.lang.Override
  public double getMinDelta() {
    return minDelta_;
  }

  public static final int TOLERANCE_FIELD_NUMBER = 5;
  private double tolerance_ = 0D;
  /**
   * <code>optional double tolerance = 5;</code>
   * @return Whether the tolerance field is set.
   */
  @java.lang.Override
  public boolean hasTolerance() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional double tolerance = 5;</code>
   * @return The tolerance.
   */
  @java.lang.Override
  public double getTolerance() {
    return tolerance_;
  }

  public static final int REPORT_FILE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reportFile_ = "";
  /**
   * <code>optional string report_file = 6;</code>
   * @return Whether the reportFile field is set.
   */
  @java.lang.Override
  public boolean hasReportFile() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string report_file = 6;</code>
   * @return The reportFile.
   */
  @java.lang.Override
  public java.lang.String getReportFile() {
    java.lang.Object ref = reportFile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportFile_ = s;
      return s;
    }
  }
  /**
   * <code>optional string report_file = 6;</code>
   * @return The bytes for reportFile.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportFileBytes() {
    java.lang.Object ref = reportFile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportFile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORT_TASK_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reportTaskId_ = "";
  /**
   * <code>optional string report_task_id = 7;</code>
   * @return Whether the reportTaskId field is set.
   */
  @java.lang.Override
  public boolean hasReportTaskId() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string report_task_id = 7;</code>
   * @return The reportTaskId.
   */
  @java.lang.Override
  public java.lang.String getReportTaskId() {
    java.lang.Object ref = reportTaskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportTaskId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string report_task_id = 7;</code>
   * @return The bytes for reportTaskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportTaskIdBytes() {
    java.lang.Object ref = reportTaskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportTaskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHT_FIELD_NUMBER = 8;
  private double weight_ = 0D;
  /**
   * <code>optional double weight = 8;</code>
   * @return Whether the weight field is set.
   */
  @java.lang.Override
  public boolean hasWeight() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional double weight = 8;</code>
   * @return The weight.
   */
  @java.lang.Override
  public double getWeight() {
    return weight_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>optional string description = 9;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string description = 9;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>optional string description = 9;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 10;
  private com.google.protobuf.Struct extensions_;
  /**
   * <code>.google.protobuf.Struct extensions = 10;</code>
   * @return Whether the extensions field is set.
   */
  @java.lang.Override
  public boolean hasExtensions() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>.google.protobuf.Struct extensions = 10;</code>
   * @return The extensions.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getExtensions() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }
  /**
   * <code>.google.protobuf.Struct extensions = 10;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(metricKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, metricKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(direction_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, direction_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeDouble(3, target_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeDouble(4, minDelta_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(5, tolerance_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, reportFile_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, reportTaskId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeDouble(8, weight_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, description_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(10, getExtensions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(metricKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, metricKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(direction_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, direction_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, target_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, minDelta_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, tolerance_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, reportFile_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, reportTaskId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, weight_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, description_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getExtensions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.monarchic.agent_protocol.v1.ObjectiveSpec)) {
      return super.equals(obj);
    }
    ai.monarchic.agent_protocol.v1.ObjectiveSpec other = (ai.monarchic.agent_protocol.v1.ObjectiveSpec) obj;

    if (!getMetricKey()
        .equals(other.getMetricKey())) return false;
    if (!getDirection()
        .equals(other.getDirection())) return false;
    if (hasTarget() != other.hasTarget()) return false;
    if (hasTarget()) {
      if (java.lang.Double.doubleToLongBits(getTarget())
          != java.lang.Double.doubleToLongBits(
              other.getTarget())) return false;
    }
    if (hasMinDelta() != other.hasMinDelta()) return false;
    if (hasMinDelta()) {
      if (java.lang.Double.doubleToLongBits(getMinDelta())
          != java.lang.Double.doubleToLongBits(
              other.getMinDelta())) return false;
    }
    if (hasTolerance() != other.hasTolerance()) return false;
    if (hasTolerance()) {
      if (java.lang.Double.doubleToLongBits(getTolerance())
          != java.lang.Double.doubleToLongBits(
              other.getTolerance())) return false;
    }
    if (hasReportFile() != other.hasReportFile()) return false;
    if (hasReportFile()) {
      if (!getReportFile()
          .equals(other.getReportFile())) return false;
    }
    if (hasReportTaskId() != other.hasReportTaskId()) return false;
    if (hasReportTaskId()) {
      if (!getReportTaskId()
          .equals(other.getReportTaskId())) return false;
    }
    if (hasWeight() != other.hasWeight()) return false;
    if (hasWeight()) {
      if (java.lang.Double.doubleToLongBits(getWeight())
          != java.lang.Double.doubleToLongBits(
              other.getWeight())) return false;
    }
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (hasExtensions() != other.hasExtensions()) return false;
    if (hasExtensions()) {
      if (!getExtensions()
          .equals(other.getExtensions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METRIC_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getMetricKey().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getDirection().hashCode();
    if (hasTarget()) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTarget()));
    }
    if (hasMinDelta()) {
      hash = (37 * hash) + MIN_DELTA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinDelta()));
    }
    if (hasTolerance()) {
      hash = (37 * hash) + TOLERANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTolerance()));
    }
    if (hasReportFile()) {
      hash = (37 * hash) + REPORT_FILE_FIELD_NUMBER;
      hash = (53 * hash) + getReportFile().hashCode();
    }
    if (hasReportTaskId()) {
      hash = (37 * hash) + REPORT_TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getReportTaskId().hashCode();
    }
    if (hasWeight()) {
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeight()));
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (hasExtensions()) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.monarchic.agent_protocol.v1.ObjectiveSpec prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code monarchic.agent_protocol.v1.ObjectiveSpec}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:monarchic.agent_protocol.v1.ObjectiveSpec)
      ai.monarchic.agent_protocol.v1.ObjectiveSpecOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.monarchic.agent_protocol.v1.ObjectiveSpec.class, ai.monarchic.agent_protocol.v1.ObjectiveSpec.Builder.class);
    }

    // Construct using ai.monarchic.agent_protocol.v1.ObjectiveSpec.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetExtensionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metricKey_ = "";
      direction_ = "";
      target_ = 0D;
      minDelta_ = 0D;
      tolerance_ = 0D;
      reportFile_ = "";
      reportTaskId_ = "";
      weight_ = 0D;
      description_ = "";
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.ObjectiveSpec getDefaultInstanceForType() {
      return ai.monarchic.agent_protocol.v1.ObjectiveSpec.getDefaultInstance();
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.ObjectiveSpec build() {
      ai.monarchic.agent_protocol.v1.ObjectiveSpec result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.ObjectiveSpec buildPartial() {
      ai.monarchic.agent_protocol.v1.ObjectiveSpec result = new ai.monarchic.agent_protocol.v1.ObjectiveSpec(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.monarchic.agent_protocol.v1.ObjectiveSpec result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metricKey_ = metricKey_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.direction_ = direction_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.target_ = target_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.minDelta_ = minDelta_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tolerance_ = tolerance_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.reportFile_ = reportFile_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.reportTaskId_ = reportTaskId_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.weight_ = weight_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.description_ = description_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.extensions_ = extensionsBuilder_ == null
            ? extensions_
            : extensionsBuilder_.build();
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.monarchic.agent_protocol.v1.ObjectiveSpec) {
        return mergeFrom((ai.monarchic.agent_protocol.v1.ObjectiveSpec)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.monarchic.agent_protocol.v1.ObjectiveSpec other) {
      if (other == ai.monarchic.agent_protocol.v1.ObjectiveSpec.getDefaultInstance()) return this;
      if (!other.getMetricKey().isEmpty()) {
        metricKey_ = other.metricKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDirection().isEmpty()) {
        direction_ = other.direction_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasTarget()) {
        setTarget(other.getTarget());
      }
      if (other.hasMinDelta()) {
        setMinDelta(other.getMinDelta());
      }
      if (other.hasTolerance()) {
        setTolerance(other.getTolerance());
      }
      if (other.hasReportFile()) {
        reportFile_ = other.reportFile_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasReportTaskId()) {
        reportTaskId_ = other.reportTaskId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.hasWeight()) {
        setWeight(other.getWeight());
      }
      if (other.hasDescription()) {
        description_ = other.description_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.hasExtensions()) {
        mergeExtensions(other.getExtensions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              metricKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              direction_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              target_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              minDelta_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              tolerance_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 50: {
              reportFile_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              reportTaskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 65: {
              weight_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 74: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  internalGetExtensionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object metricKey_ = "";
    /**
     * <code>string metric_key = 1;</code>
     * @return The metricKey.
     */
    public java.lang.String getMetricKey() {
      java.lang.Object ref = metricKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metricKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string metric_key = 1;</code>
     * @return The bytes for metricKey.
     */
    public com.google.protobuf.ByteString
        getMetricKeyBytes() {
      java.lang.Object ref = metricKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metricKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string metric_key = 1;</code>
     * @param value The metricKey to set.
     * @return This builder for chaining.
     */
    public Builder setMetricKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      metricKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string metric_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetricKey() {
      metricKey_ = getDefaultInstance().getMetricKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string metric_key = 1;</code>
     * @param value The bytes for metricKey to set.
     * @return This builder for chaining.
     */
    public Builder setMetricKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      metricKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object direction_ = "";
    /**
     * <code>string direction = 2;</code>
     * @return The direction.
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string direction = 2;</code>
     * @return The bytes for direction.
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string direction = 2;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      direction_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string direction = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      direction_ = getDefaultInstance().getDirection();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string direction = 2;</code>
     * @param value The bytes for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      direction_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double target_ ;
    /**
     * <code>optional double target = 3;</code>
     * @return Whether the target field is set.
     */
    @java.lang.Override
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional double target = 3;</code>
     * @return The target.
     */
    @java.lang.Override
    public double getTarget() {
      return target_;
    }
    /**
     * <code>optional double target = 3;</code>
     * @param value The target to set.
     * @return This builder for chaining.
     */
    public Builder setTarget(double value) {

      target_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional double target = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTarget() {
      bitField0_ = (bitField0_ & ~0x00000004);
      target_ = 0D;
      onChanged();
      return this;
    }

    private double minDelta_ ;
    /**
     * <code>optional double min_delta = 4;</code>
     * @return Whether the minDelta field is set.
     */
    @java.lang.Override
    public boolean hasMinDelta() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double min_delta = 4;</code>
     * @return The minDelta.
     */
    @java.lang.Override
    public double getMinDelta() {
      return minDelta_;
    }
    /**
     * <code>optional double min_delta = 4;</code>
     * @param value The minDelta to set.
     * @return This builder for chaining.
     */
    public Builder setMinDelta(double value) {

      minDelta_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional double min_delta = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinDelta() {
      bitField0_ = (bitField0_ & ~0x00000008);
      minDelta_ = 0D;
      onChanged();
      return this;
    }

    private double tolerance_ ;
    /**
     * <code>optional double tolerance = 5;</code>
     * @return Whether the tolerance field is set.
     */
    @java.lang.Override
    public boolean hasTolerance() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional double tolerance = 5;</code>
     * @return The tolerance.
     */
    @java.lang.Override
    public double getTolerance() {
      return tolerance_;
    }
    /**
     * <code>optional double tolerance = 5;</code>
     * @param value The tolerance to set.
     * @return This builder for chaining.
     */
    public Builder setTolerance(double value) {

      tolerance_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional double tolerance = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTolerance() {
      bitField0_ = (bitField0_ & ~0x00000010);
      tolerance_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object reportFile_ = "";
    /**
     * <code>optional string report_file = 6;</code>
     * @return Whether the reportFile field is set.
     */
    public boolean hasReportFile() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string report_file = 6;</code>
     * @return The reportFile.
     */
    public java.lang.String getReportFile() {
      java.lang.Object ref = reportFile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportFile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string report_file = 6;</code>
     * @return The bytes for reportFile.
     */
    public com.google.protobuf.ByteString
        getReportFileBytes() {
      java.lang.Object ref = reportFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string report_file = 6;</code>
     * @param value The reportFile to set.
     * @return This builder for chaining.
     */
    public Builder setReportFile(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reportFile_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string report_file = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportFile() {
      reportFile_ = getDefaultInstance().getReportFile();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string report_file = 6;</code>
     * @param value The bytes for reportFile to set.
     * @return This builder for chaining.
     */
    public Builder setReportFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportFile_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object reportTaskId_ = "";
    /**
     * <code>optional string report_task_id = 7;</code>
     * @return Whether the reportTaskId field is set.
     */
    public boolean hasReportTaskId() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string report_task_id = 7;</code>
     * @return The reportTaskId.
     */
    public java.lang.String getReportTaskId() {
      java.lang.Object ref = reportTaskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportTaskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string report_task_id = 7;</code>
     * @return The bytes for reportTaskId.
     */
    public com.google.protobuf.ByteString
        getReportTaskIdBytes() {
      java.lang.Object ref = reportTaskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportTaskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string report_task_id = 7;</code>
     * @param value The reportTaskId to set.
     * @return This builder for chaining.
     */
    public Builder setReportTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reportTaskId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional string report_task_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportTaskId() {
      reportTaskId_ = getDefaultInstance().getReportTaskId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>optional string report_task_id = 7;</code>
     * @param value The bytes for reportTaskId to set.
     * @return This builder for chaining.
     */
    public Builder setReportTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportTaskId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private double weight_ ;
    /**
     * <code>optional double weight = 8;</code>
     * @return Whether the weight field is set.
     */
    @java.lang.Override
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional double weight = 8;</code>
     * @return The weight.
     */
    @java.lang.Override
    public double getWeight() {
      return weight_;
    }
    /**
     * <code>optional double weight = 8;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(double value) {

      weight_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional double weight = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      bitField0_ = (bitField0_ & ~0x00000080);
      weight_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 9;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string description = 9;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 9;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 9;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 9;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct extensions_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> extensionsBuilder_;
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     * @return Whether the extensions field is set.
     */
    public boolean hasExtensions() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     * @return The extensions.
     */
    public com.google.protobuf.Struct getExtensions() {
      if (extensionsBuilder_ == null) {
        return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      } else {
        return extensionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     */
    public Builder setExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        extensions_ = value;
      } else {
        extensionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     */
    public Builder setExtensions(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        extensions_ = builderForValue.build();
      } else {
        extensionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     */
    public Builder mergeExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          extensions_ != null &&
          extensions_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getExtensionsBuilder().mergeFrom(value);
        } else {
          extensions_ = value;
        }
      } else {
        extensionsBuilder_.mergeFrom(value);
      }
      if (extensions_ != null) {
        bitField0_ |= 0x00000200;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     */
    public Builder clearExtensions() {
      bitField0_ = (bitField0_ & ~0x00000200);
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     */
    public com.google.protobuf.Struct.Builder getExtensionsBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return internalGetExtensionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     */
    public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
      if (extensionsBuilder_ != null) {
        return extensionsBuilder_.getMessageOrBuilder();
      } else {
        return extensions_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        internalGetExtensionsFieldBuilder() {
      if (extensionsBuilder_ == null) {
        extensionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getExtensions(),
                getParentForChildren(),
                isClean());
        extensions_ = null;
      }
      return extensionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:monarchic.agent_protocol.v1.ObjectiveSpec)
  }

  // @@protoc_insertion_point(class_scope:monarchic.agent_protocol.v1.ObjectiveSpec)
  private static final ai.monarchic.agent_protocol.v1.ObjectiveSpec DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.monarchic.agent_protocol.v1.ObjectiveSpec();
  }

  public static ai.monarchic.agent_protocol.v1.ObjectiveSpec getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ObjectiveSpec>
      PARSER = new com.google.protobuf.AbstractParser<ObjectiveSpec>() {
    @java.lang.Override
    public ObjectiveSpec parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ObjectiveSpec> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ObjectiveSpec> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.ObjectiveSpec getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

