// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface RunContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.RunContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string repo = 2;</code>
   * @return The repo.
   */
  java.lang.String getRepo();
  /**
   * <code>string repo = 2;</code>
   * @return The bytes for repo.
   */
  com.google.protobuf.ByteString
      getRepoBytes();

  /**
   * <code>string worktree = 3;</code>
   * @return The worktree.
   */
  java.lang.String getWorktree();
  /**
   * <code>string worktree = 3;</code>
   * @return The bytes for worktree.
   */
  com.google.protobuf.ByteString
      getWorktreeBytes();

  /**
   * <code>string image = 4;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 4;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>string runner = 5;</code>
   * @return The runner.
   */
  java.lang.String getRunner();
  /**
   * <code>string runner = 5;</code>
   * @return The bytes for runner.
   */
  com.google.protobuf.ByteString
      getRunnerBytes();

  /**
   * <code>repeated string labels = 6;</code>
   * @return A list containing the labels.
   */
  java.util.List<java.lang.String>
      getLabelsList();
  /**
   * <code>repeated string labels = 6;</code>
   * @return The count of labels.
   */
  int getLabelsCount();
  /**
   * <code>repeated string labels = 6;</code>
   * @param index The index of the element to return.
   * @return The labels at the given index.
   */
  java.lang.String getLabels(int index);
  /**
   * <code>repeated string labels = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the labels at the given index.
   */
  com.google.protobuf.ByteString
      getLabelsBytes(int index);

  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();
}
