// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monarchic_agent_protocol.proto

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf type {@code monarchic.agent_protocol.v1.Task}
 */
public final class Task extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:monarchic.agent_protocol.v1.Task)
    TaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Task.newBuilder() to construct.
  private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Task() {
    version_ = "";
    taskId_ = "";
    role_ = 0;
    goal_ = "";
    gatesRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Task();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Task_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Task_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.monarchic.agent_protocol.v1.Task.class, ai.monarchic.agent_protocol.v1.Task.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskId_ = "";
  /**
   * <code>string task_id = 2;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_id = 2;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLE_FIELD_NUMBER = 3;
  private int role_ = 0;
  /**
   * <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
   * @return The enum numeric value on the wire for role.
   */
  @java.lang.Override public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
   * @return The role.
   */
  @java.lang.Override public ai.monarchic.agent_protocol.v1.AgentRole getRole() {
    ai.monarchic.agent_protocol.v1.AgentRole result = ai.monarchic.agent_protocol.v1.AgentRole.forNumber(role_);
    return result == null ? ai.monarchic.agent_protocol.v1.AgentRole.UNRECOGNIZED : result;
  }

  public static final int GOAL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object goal_ = "";
  /**
   * <code>string goal = 4;</code>
   * @return The goal.
   */
  @java.lang.Override
  public java.lang.String getGoal() {
    java.lang.Object ref = goal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      goal_ = s;
      return s;
    }
  }
  /**
   * <code>string goal = 4;</code>
   * @return The bytes for goal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGoalBytes() {
    java.lang.Object ref = goal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      goal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUTS_FIELD_NUMBER = 5;
  private com.google.protobuf.Struct inputs_;
  /**
   * <code>.google.protobuf.Struct inputs = 5;</code>
   * @return Whether the inputs field is set.
   */
  @java.lang.Override
  public boolean hasInputs() {
    return inputs_ != null;
  }
  /**
   * <code>.google.protobuf.Struct inputs = 5;</code>
   * @return The inputs.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getInputs() {
    return inputs_ == null ? com.google.protobuf.Struct.getDefaultInstance() : inputs_;
  }
  /**
   * <code>.google.protobuf.Struct inputs = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getInputsOrBuilder() {
    return inputs_ == null ? com.google.protobuf.Struct.getDefaultInstance() : inputs_;
  }

  public static final int CONSTRAINTS_FIELD_NUMBER = 6;
  private com.google.protobuf.Struct constraints_;
  /**
   * <code>.google.protobuf.Struct constraints = 6;</code>
   * @return Whether the constraints field is set.
   */
  @java.lang.Override
  public boolean hasConstraints() {
    return constraints_ != null;
  }
  /**
   * <code>.google.protobuf.Struct constraints = 6;</code>
   * @return The constraints.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getConstraints() {
    return constraints_ == null ? com.google.protobuf.Struct.getDefaultInstance() : constraints_;
  }
  /**
   * <code>.google.protobuf.Struct constraints = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getConstraintsOrBuilder() {
    return constraints_ == null ? com.google.protobuf.Struct.getDefaultInstance() : constraints_;
  }

  public static final int GATES_REQUIRED_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList gatesRequired_;
  /**
   * <code>repeated string gates_required = 7;</code>
   * @return A list containing the gatesRequired.
   */
  public com.google.protobuf.ProtocolStringList
      getGatesRequiredList() {
    return gatesRequired_;
  }
  /**
   * <code>repeated string gates_required = 7;</code>
   * @return The count of gatesRequired.
   */
  public int getGatesRequiredCount() {
    return gatesRequired_.size();
  }
  /**
   * <code>repeated string gates_required = 7;</code>
   * @param index The index of the element to return.
   * @return The gatesRequired at the given index.
   */
  public java.lang.String getGatesRequired(int index) {
    return gatesRequired_.get(index);
  }
  /**
   * <code>repeated string gates_required = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the gatesRequired at the given index.
   */
  public com.google.protobuf.ByteString
      getGatesRequiredBytes(int index) {
    return gatesRequired_.getByteString(index);
  }

  public static final int RUN_CONTEXT_FIELD_NUMBER = 8;
  private ai.monarchic.agent_protocol.v1.RunContext runContext_;
  /**
   * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
   * @return Whether the runContext field is set.
   */
  @java.lang.Override
  public boolean hasRunContext() {
    return runContext_ != null;
  }
  /**
   * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
   * @return The runContext.
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.RunContext getRunContext() {
    return runContext_ == null ? ai.monarchic.agent_protocol.v1.RunContext.getDefaultInstance() : runContext_;
  }
  /**
   * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.RunContextOrBuilder getRunContextOrBuilder() {
    return runContext_ == null ? ai.monarchic.agent_protocol.v1.RunContext.getDefaultInstance() : runContext_;
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 9;
  private com.google.protobuf.Struct extensions_;
  /**
   * <code>.google.protobuf.Struct extensions = 9;</code>
   * @return Whether the extensions field is set.
   */
  @java.lang.Override
  public boolean hasExtensions() {
    return extensions_ != null;
  }
  /**
   * <code>.google.protobuf.Struct extensions = 9;</code>
   * @return The extensions.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getExtensions() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }
  /**
   * <code>.google.protobuf.Struct extensions = 9;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskId_);
    }
    if (role_ != ai.monarchic.agent_protocol.v1.AgentRole.AGENT_ROLE_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, role_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(goal_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, goal_);
    }
    if (inputs_ != null) {
      output.writeMessage(5, getInputs());
    }
    if (constraints_ != null) {
      output.writeMessage(6, getConstraints());
    }
    for (int i = 0; i < gatesRequired_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, gatesRequired_.getRaw(i));
    }
    if (runContext_ != null) {
      output.writeMessage(8, getRunContext());
    }
    if (extensions_ != null) {
      output.writeMessage(9, getExtensions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskId_);
    }
    if (role_ != ai.monarchic.agent_protocol.v1.AgentRole.AGENT_ROLE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, role_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(goal_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, goal_);
    }
    if (inputs_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getInputs());
    }
    if (constraints_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getConstraints());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < gatesRequired_.size(); i++) {
        dataSize += computeStringSizeNoTag(gatesRequired_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGatesRequiredList().size();
    }
    if (runContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getRunContext());
    }
    if (extensions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getExtensions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.monarchic.agent_protocol.v1.Task)) {
      return super.equals(obj);
    }
    ai.monarchic.agent_protocol.v1.Task other = (ai.monarchic.agent_protocol.v1.Task) obj;

    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (role_ != other.role_) return false;
    if (!getGoal()
        .equals(other.getGoal())) return false;
    if (hasInputs() != other.hasInputs()) return false;
    if (hasInputs()) {
      if (!getInputs()
          .equals(other.getInputs())) return false;
    }
    if (hasConstraints() != other.hasConstraints()) return false;
    if (hasConstraints()) {
      if (!getConstraints()
          .equals(other.getConstraints())) return false;
    }
    if (!getGatesRequiredList()
        .equals(other.getGatesRequiredList())) return false;
    if (hasRunContext() != other.hasRunContext()) return false;
    if (hasRunContext()) {
      if (!getRunContext()
          .equals(other.getRunContext())) return false;
    }
    if (hasExtensions() != other.hasExtensions()) return false;
    if (hasExtensions()) {
      if (!getExtensions()
          .equals(other.getExtensions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + role_;
    hash = (37 * hash) + GOAL_FIELD_NUMBER;
    hash = (53 * hash) + getGoal().hashCode();
    if (hasInputs()) {
      hash = (37 * hash) + INPUTS_FIELD_NUMBER;
      hash = (53 * hash) + getInputs().hashCode();
    }
    if (hasConstraints()) {
      hash = (37 * hash) + CONSTRAINTS_FIELD_NUMBER;
      hash = (53 * hash) + getConstraints().hashCode();
    }
    if (getGatesRequiredCount() > 0) {
      hash = (37 * hash) + GATES_REQUIRED_FIELD_NUMBER;
      hash = (53 * hash) + getGatesRequiredList().hashCode();
    }
    if (hasRunContext()) {
      hash = (37 * hash) + RUN_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getRunContext().hashCode();
    }
    if (hasExtensions()) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.Task parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.monarchic.agent_protocol.v1.Task prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code monarchic.agent_protocol.v1.Task}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:monarchic.agent_protocol.v1.Task)
      ai.monarchic.agent_protocol.v1.TaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Task_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.monarchic.agent_protocol.v1.Task.class, ai.monarchic.agent_protocol.v1.Task.Builder.class);
    }

    // Construct using ai.monarchic.agent_protocol.v1.Task.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = "";
      taskId_ = "";
      role_ = 0;
      goal_ = "";
      inputs_ = null;
      if (inputsBuilder_ != null) {
        inputsBuilder_.dispose();
        inputsBuilder_ = null;
      }
      constraints_ = null;
      if (constraintsBuilder_ != null) {
        constraintsBuilder_.dispose();
        constraintsBuilder_ = null;
      }
      gatesRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      runContext_ = null;
      if (runContextBuilder_ != null) {
        runContextBuilder_.dispose();
        runContextBuilder_ = null;
      }
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_Task_descriptor;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.Task getDefaultInstanceForType() {
      return ai.monarchic.agent_protocol.v1.Task.getDefaultInstance();
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.Task build() {
      ai.monarchic.agent_protocol.v1.Task result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.Task buildPartial() {
      ai.monarchic.agent_protocol.v1.Task result = new ai.monarchic.agent_protocol.v1.Task(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.monarchic.agent_protocol.v1.Task result) {
      if (((bitField0_ & 0x00000040) != 0)) {
        gatesRequired_ = gatesRequired_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.gatesRequired_ = gatesRequired_;
    }

    private void buildPartial0(ai.monarchic.agent_protocol.v1.Task result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.taskId_ = taskId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.role_ = role_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.goal_ = goal_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.inputs_ = inputsBuilder_ == null
            ? inputs_
            : inputsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.constraints_ = constraintsBuilder_ == null
            ? constraints_
            : constraintsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.runContext_ = runContextBuilder_ == null
            ? runContext_
            : runContextBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.extensions_ = extensionsBuilder_ == null
            ? extensions_
            : extensionsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.monarchic.agent_protocol.v1.Task) {
        return mergeFrom((ai.monarchic.agent_protocol.v1.Task)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.monarchic.agent_protocol.v1.Task other) {
      if (other == ai.monarchic.agent_protocol.v1.Task.getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.role_ != 0) {
        setRoleValue(other.getRoleValue());
      }
      if (!other.getGoal().isEmpty()) {
        goal_ = other.goal_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasInputs()) {
        mergeInputs(other.getInputs());
      }
      if (other.hasConstraints()) {
        mergeConstraints(other.getConstraints());
      }
      if (!other.gatesRequired_.isEmpty()) {
        if (gatesRequired_.isEmpty()) {
          gatesRequired_ = other.gatesRequired_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureGatesRequiredIsMutable();
          gatesRequired_.addAll(other.gatesRequired_);
        }
        onChanged();
      }
      if (other.hasRunContext()) {
        mergeRunContext(other.getRunContext());
      }
      if (other.hasExtensions()) {
        mergeExtensions(other.getExtensions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              role_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              goal_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getInputsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getConstraintsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureGatesRequiredIsMutable();
              gatesRequired_.add(s);
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getRunContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getExtensionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <code>string task_id = 2;</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_id = 2;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_id = 2;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 2;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int role_ = 0;
    /**
     * <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     * @return The enum numeric value on the wire for role.
     */
    @java.lang.Override public int getRoleValue() {
      return role_;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     * @param value The enum numeric value on the wire for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleValue(int value) {
      role_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     * @return The role.
     */
    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.AgentRole getRole() {
      ai.monarchic.agent_protocol.v1.AgentRole result = ai.monarchic.agent_protocol.v1.AgentRole.forNumber(role_);
      return result == null ? ai.monarchic.agent_protocol.v1.AgentRole.UNRECOGNIZED : result;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(ai.monarchic.agent_protocol.v1.AgentRole value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      role_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      bitField0_ = (bitField0_ & ~0x00000004);
      role_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object goal_ = "";
    /**
     * <code>string goal = 4;</code>
     * @return The goal.
     */
    public java.lang.String getGoal() {
      java.lang.Object ref = goal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        goal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string goal = 4;</code>
     * @return The bytes for goal.
     */
    public com.google.protobuf.ByteString
        getGoalBytes() {
      java.lang.Object ref = goal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string goal = 4;</code>
     * @param value The goal to set.
     * @return This builder for chaining.
     */
    public Builder setGoal(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      goal_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string goal = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoal() {
      goal_ = getDefaultInstance().getGoal();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string goal = 4;</code>
     * @param value The bytes for goal to set.
     * @return This builder for chaining.
     */
    public Builder setGoalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      goal_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct inputs_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> inputsBuilder_;
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     * @return Whether the inputs field is set.
     */
    public boolean hasInputs() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     * @return The inputs.
     */
    public com.google.protobuf.Struct getInputs() {
      if (inputsBuilder_ == null) {
        return inputs_ == null ? com.google.protobuf.Struct.getDefaultInstance() : inputs_;
      } else {
        return inputsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     */
    public Builder setInputs(com.google.protobuf.Struct value) {
      if (inputsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inputs_ = value;
      } else {
        inputsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     */
    public Builder setInputs(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (inputsBuilder_ == null) {
        inputs_ = builderForValue.build();
      } else {
        inputsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     */
    public Builder mergeInputs(com.google.protobuf.Struct value) {
      if (inputsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          inputs_ != null &&
          inputs_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getInputsBuilder().mergeFrom(value);
        } else {
          inputs_ = value;
        }
      } else {
        inputsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     */
    public Builder clearInputs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      inputs_ = null;
      if (inputsBuilder_ != null) {
        inputsBuilder_.dispose();
        inputsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     */
    public com.google.protobuf.Struct.Builder getInputsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getInputsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     */
    public com.google.protobuf.StructOrBuilder getInputsOrBuilder() {
      if (inputsBuilder_ != null) {
        return inputsBuilder_.getMessageOrBuilder();
      } else {
        return inputs_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : inputs_;
      }
    }
    /**
     * <code>.google.protobuf.Struct inputs = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getInputsFieldBuilder() {
      if (inputsBuilder_ == null) {
        inputsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getInputs(),
                getParentForChildren(),
                isClean());
        inputs_ = null;
      }
      return inputsBuilder_;
    }

    private com.google.protobuf.Struct constraints_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> constraintsBuilder_;
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     * @return Whether the constraints field is set.
     */
    public boolean hasConstraints() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     * @return The constraints.
     */
    public com.google.protobuf.Struct getConstraints() {
      if (constraintsBuilder_ == null) {
        return constraints_ == null ? com.google.protobuf.Struct.getDefaultInstance() : constraints_;
      } else {
        return constraintsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     */
    public Builder setConstraints(com.google.protobuf.Struct value) {
      if (constraintsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        constraints_ = value;
      } else {
        constraintsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     */
    public Builder setConstraints(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (constraintsBuilder_ == null) {
        constraints_ = builderForValue.build();
      } else {
        constraintsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     */
    public Builder mergeConstraints(com.google.protobuf.Struct value) {
      if (constraintsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          constraints_ != null &&
          constraints_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getConstraintsBuilder().mergeFrom(value);
        } else {
          constraints_ = value;
        }
      } else {
        constraintsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     */
    public Builder clearConstraints() {
      bitField0_ = (bitField0_ & ~0x00000020);
      constraints_ = null;
      if (constraintsBuilder_ != null) {
        constraintsBuilder_.dispose();
        constraintsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     */
    public com.google.protobuf.Struct.Builder getConstraintsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getConstraintsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     */
    public com.google.protobuf.StructOrBuilder getConstraintsOrBuilder() {
      if (constraintsBuilder_ != null) {
        return constraintsBuilder_.getMessageOrBuilder();
      } else {
        return constraints_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : constraints_;
      }
    }
    /**
     * <code>.google.protobuf.Struct constraints = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getConstraintsFieldBuilder() {
      if (constraintsBuilder_ == null) {
        constraintsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getConstraints(),
                getParentForChildren(),
                isClean());
        constraints_ = null;
      }
      return constraintsBuilder_;
    }

    private com.google.protobuf.LazyStringList gatesRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureGatesRequiredIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        gatesRequired_ = new com.google.protobuf.LazyStringArrayList(gatesRequired_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @return A list containing the gatesRequired.
     */
    public com.google.protobuf.ProtocolStringList
        getGatesRequiredList() {
      return gatesRequired_.getUnmodifiableView();
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @return The count of gatesRequired.
     */
    public int getGatesRequiredCount() {
      return gatesRequired_.size();
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @param index The index of the element to return.
     * @return The gatesRequired at the given index.
     */
    public java.lang.String getGatesRequired(int index) {
      return gatesRequired_.get(index);
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the gatesRequired at the given index.
     */
    public com.google.protobuf.ByteString
        getGatesRequiredBytes(int index) {
      return gatesRequired_.getByteString(index);
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @param index The index to set the value at.
     * @param value The gatesRequired to set.
     * @return This builder for chaining.
     */
    public Builder setGatesRequired(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGatesRequiredIsMutable();
      gatesRequired_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @param value The gatesRequired to add.
     * @return This builder for chaining.
     */
    public Builder addGatesRequired(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGatesRequiredIsMutable();
      gatesRequired_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @param values The gatesRequired to add.
     * @return This builder for chaining.
     */
    public Builder addAllGatesRequired(
        java.lang.Iterable<java.lang.String> values) {
      ensureGatesRequiredIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, gatesRequired_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearGatesRequired() {
      gatesRequired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string gates_required = 7;</code>
     * @param value The bytes of the gatesRequired to add.
     * @return This builder for chaining.
     */
    public Builder addGatesRequiredBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureGatesRequiredIsMutable();
      gatesRequired_.add(value);
      onChanged();
      return this;
    }

    private ai.monarchic.agent_protocol.v1.RunContext runContext_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.monarchic.agent_protocol.v1.RunContext, ai.monarchic.agent_protocol.v1.RunContext.Builder, ai.monarchic.agent_protocol.v1.RunContextOrBuilder> runContextBuilder_;
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     * @return Whether the runContext field is set.
     */
    public boolean hasRunContext() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     * @return The runContext.
     */
    public ai.monarchic.agent_protocol.v1.RunContext getRunContext() {
      if (runContextBuilder_ == null) {
        return runContext_ == null ? ai.monarchic.agent_protocol.v1.RunContext.getDefaultInstance() : runContext_;
      } else {
        return runContextBuilder_.getMessage();
      }
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    public Builder setRunContext(ai.monarchic.agent_protocol.v1.RunContext value) {
      if (runContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        runContext_ = value;
      } else {
        runContextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    public Builder setRunContext(
        ai.monarchic.agent_protocol.v1.RunContext.Builder builderForValue) {
      if (runContextBuilder_ == null) {
        runContext_ = builderForValue.build();
      } else {
        runContextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    public Builder mergeRunContext(ai.monarchic.agent_protocol.v1.RunContext value) {
      if (runContextBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          runContext_ != null &&
          runContext_ != ai.monarchic.agent_protocol.v1.RunContext.getDefaultInstance()) {
          getRunContextBuilder().mergeFrom(value);
        } else {
          runContext_ = value;
        }
      } else {
        runContextBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    public Builder clearRunContext() {
      bitField0_ = (bitField0_ & ~0x00000080);
      runContext_ = null;
      if (runContextBuilder_ != null) {
        runContextBuilder_.dispose();
        runContextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.RunContext.Builder getRunContextBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getRunContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.RunContextOrBuilder getRunContextOrBuilder() {
      if (runContextBuilder_ != null) {
        return runContextBuilder_.getMessageOrBuilder();
      } else {
        return runContext_ == null ?
            ai.monarchic.agent_protocol.v1.RunContext.getDefaultInstance() : runContext_;
      }
    }
    /**
     * <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.monarchic.agent_protocol.v1.RunContext, ai.monarchic.agent_protocol.v1.RunContext.Builder, ai.monarchic.agent_protocol.v1.RunContextOrBuilder> 
        getRunContextFieldBuilder() {
      if (runContextBuilder_ == null) {
        runContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.monarchic.agent_protocol.v1.RunContext, ai.monarchic.agent_protocol.v1.RunContext.Builder, ai.monarchic.agent_protocol.v1.RunContextOrBuilder>(
                getRunContext(),
                getParentForChildren(),
                isClean());
        runContext_ = null;
      }
      return runContextBuilder_;
    }

    private com.google.protobuf.Struct extensions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> extensionsBuilder_;
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     * @return Whether the extensions field is set.
     */
    public boolean hasExtensions() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     * @return The extensions.
     */
    public com.google.protobuf.Struct getExtensions() {
      if (extensionsBuilder_ == null) {
        return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      } else {
        return extensionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     */
    public Builder setExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        extensions_ = value;
      } else {
        extensionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     */
    public Builder setExtensions(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        extensions_ = builderForValue.build();
      } else {
        extensionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     */
    public Builder mergeExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          extensions_ != null &&
          extensions_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getExtensionsBuilder().mergeFrom(value);
        } else {
          extensions_ = value;
        }
      } else {
        extensionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     */
    public Builder clearExtensions() {
      bitField0_ = (bitField0_ & ~0x00000100);
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     */
    public com.google.protobuf.Struct.Builder getExtensionsBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getExtensionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     */
    public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
      if (extensionsBuilder_ != null) {
        return extensionsBuilder_.getMessageOrBuilder();
      } else {
        return extensions_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getExtensionsFieldBuilder() {
      if (extensionsBuilder_ == null) {
        extensionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getExtensions(),
                getParentForChildren(),
                isClean());
        extensions_ = null;
      }
      return extensionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:monarchic.agent_protocol.v1.Task)
  }

  // @@protoc_insertion_point(class_scope:monarchic.agent_protocol.v1.Task)
  private static final ai.monarchic.agent_protocol.v1.Task DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.monarchic.agent_protocol.v1.Task();
  }

  public static ai.monarchic.agent_protocol.v1.Task getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Task>
      PARSER = new com.google.protobuf.AbstractParser<Task>() {
    @java.lang.Override
    public Task parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Task> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Task> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.Task getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

