<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.AcceptanceCriteria</code>
 */
class AcceptanceCriteria extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     */
    protected $metric = '';
    /**
     * Generated from protobuf field <code>string direction = 2;</code>
     */
    protected $direction = '';
    /**
     * Generated from protobuf field <code>double threshold = 3;</code>
     */
    protected $threshold = 0.0;
    /**
     * Generated from protobuf field <code>optional double min_effect_size = 4;</code>
     */
    protected $min_effect_size = null;
    /**
     * Generated from protobuf field <code>optional double max_variance = 5;</code>
     */
    protected $max_variance = null;
    /**
     * Generated from protobuf field <code>optional double confidence_level = 6;</code>
     */
    protected $confidence_level = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     */
    protected $extensions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $metric
     *     @type string $direction
     *     @type float $threshold
     *     @type float $min_effect_size
     *     @type float $max_variance
     *     @type float $confidence_level
     *     @type \Google\Protobuf\Struct $extensions
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     * @return string
     */
    public function getMetric()
    {
        return $this->metric;
    }

    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMetric($var)
    {
        GPBUtil::checkString($var, True);
        $this->metric = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string direction = 2;</code>
     * @return string
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * Generated from protobuf field <code>string direction = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkString($var, True);
        $this->direction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double threshold = 3;</code>
     * @return float
     */
    public function getThreshold()
    {
        return $this->threshold;
    }

    /**
     * Generated from protobuf field <code>double threshold = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setThreshold($var)
    {
        GPBUtil::checkDouble($var);
        $this->threshold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double min_effect_size = 4;</code>
     * @return float
     */
    public function getMinEffectSize()
    {
        return isset($this->min_effect_size) ? $this->min_effect_size : 0.0;
    }

    public function hasMinEffectSize()
    {
        return isset($this->min_effect_size);
    }

    public function clearMinEffectSize()
    {
        unset($this->min_effect_size);
    }

    /**
     * Generated from protobuf field <code>optional double min_effect_size = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setMinEffectSize($var)
    {
        GPBUtil::checkDouble($var);
        $this->min_effect_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double max_variance = 5;</code>
     * @return float
     */
    public function getMaxVariance()
    {
        return isset($this->max_variance) ? $this->max_variance : 0.0;
    }

    public function hasMaxVariance()
    {
        return isset($this->max_variance);
    }

    public function clearMaxVariance()
    {
        unset($this->max_variance);
    }

    /**
     * Generated from protobuf field <code>optional double max_variance = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxVariance($var)
    {
        GPBUtil::checkDouble($var);
        $this->max_variance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double confidence_level = 6;</code>
     * @return float
     */
    public function getConfidenceLevel()
    {
        return isset($this->confidence_level) ? $this->confidence_level : 0.0;
    }

    public function hasConfidenceLevel()
    {
        return isset($this->confidence_level);
    }

    public function clearConfidenceLevel()
    {
        unset($this->confidence_level);
    }

    /**
     * Generated from protobuf field <code>optional double confidence_level = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setConfidenceLevel($var)
    {
        GPBUtil::checkDouble($var);
        $this->confidence_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

}

