<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.Artifact</code>
 */
class Artifact extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>string artifact_id = 2;</code>
     */
    protected $artifact_id = '';
    /**
     * Generated from protobuf field <code>string type = 3;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string summary = 4;</code>
     */
    protected $summary = '';
    /**
     * Generated from protobuf field <code>string path = 5;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>string task_id = 6;</code>
     */
    protected $task_id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     */
    protected $extensions = null;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    protected $provenance = null;
    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
     */
    private $dataset_refs;
    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
     */
    private $eval_results;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 11;</code>
     */
    protected $experiment_spec = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type string $artifact_id
     *     @type string $type
     *     @type string $summary
     *     @type string $path
     *     @type string $task_id
     *     @type \Google\Protobuf\Struct $extensions
     *     @type \Monarchic\AgentProtocol\V1\Provenance $provenance
     *     @type \Monarchic\AgentProtocol\V1\DatasetRef[] $dataset_refs
     *     @type \Monarchic\AgentProtocol\V1\EvalResult[] $eval_results
     *     @type \Monarchic\AgentProtocol\V1\ExperimentSpec $experiment_spec
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string artifact_id = 2;</code>
     * @return string
     */
    public function getArtifactId()
    {
        return $this->artifact_id;
    }

    /**
     * Generated from protobuf field <code>string artifact_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifactId($var)
    {
        GPBUtil::checkString($var, True);
        $this->artifact_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string summary = 4;</code>
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>string summary = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 5;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string task_id = 6;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>string task_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     * @return \Monarchic\AgentProtocol\V1\Provenance|null
     */
    public function getProvenance()
    {
        return $this->provenance;
    }

    public function hasProvenance()
    {
        return isset($this->provenance);
    }

    public function clearProvenance()
    {
        unset($this->provenance);
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     * @param \Monarchic\AgentProtocol\V1\Provenance $var
     * @return $this
     */
    public function setProvenance($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\Provenance::class);
        $this->provenance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
     * @return RepeatedField<\Monarchic\AgentProtocol\V1\DatasetRef>
     */
    public function getDatasetRefs()
    {
        return $this->dataset_refs;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 9;</code>
     * @param \Monarchic\AgentProtocol\V1\DatasetRef[] $var
     * @return $this
     */
    public function setDatasetRefs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Monarchic\AgentProtocol\V1\DatasetRef::class);
        $this->dataset_refs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
     * @return RepeatedField<\Monarchic\AgentProtocol\V1\EvalResult>
     */
    public function getEvalResults()
    {
        return $this->eval_results;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 10;</code>
     * @param \Monarchic\AgentProtocol\V1\EvalResult[] $var
     * @return $this
     */
    public function setEvalResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Monarchic\AgentProtocol\V1\EvalResult::class);
        $this->eval_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 11;</code>
     * @return \Monarchic\AgentProtocol\V1\ExperimentSpec|null
     */
    public function getExperimentSpec()
    {
        return $this->experiment_spec;
    }

    public function hasExperimentSpec()
    {
        return isset($this->experiment_spec);
    }

    public function clearExperimentSpec()
    {
        unset($this->experiment_spec);
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 11;</code>
     * @param \Monarchic\AgentProtocol\V1\ExperimentSpec $var
     * @return $this
     */
    public function setExperimentSpec($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\ExperimentSpec::class);
        $this->experiment_spec = $var;

        return $this;
    }

}

