<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.EvalResult</code>
 */
class EvalResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     */
    protected $metric = '';
    /**
     * Generated from protobuf field <code>double value = 2;</code>
     */
    protected $value = 0.0;
    /**
     * Generated from protobuf field <code>optional double lower_ci = 3;</code>
     */
    protected $lower_ci = null;
    /**
     * Generated from protobuf field <code>optional double upper_ci = 4;</code>
     */
    protected $upper_ci = null;
    /**
     * Generated from protobuf field <code>optional double variance = 5;</code>
     */
    protected $variance = null;
    /**
     * Generated from protobuf field <code>optional int64 seed = 6;</code>
     */
    protected $seed = null;
    /**
     * Generated from protobuf field <code>bool passed = 7;</code>
     */
    protected $passed = false;
    /**
     * Generated from protobuf field <code>optional string notes = 8;</code>
     */
    protected $notes = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 9;</code>
     */
    protected $extensions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $metric
     *     @type float $value
     *     @type float $lower_ci
     *     @type float $upper_ci
     *     @type float $variance
     *     @type int|string $seed
     *     @type bool $passed
     *     @type string $notes
     *     @type \Google\Protobuf\Struct $extensions
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     * @return string
     */
    public function getMetric()
    {
        return $this->metric;
    }

    /**
     * Generated from protobuf field <code>string metric = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMetric($var)
    {
        GPBUtil::checkString($var, True);
        $this->metric = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double value = 2;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>double value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double lower_ci = 3;</code>
     * @return float
     */
    public function getLowerCi()
    {
        return isset($this->lower_ci) ? $this->lower_ci : 0.0;
    }

    public function hasLowerCi()
    {
        return isset($this->lower_ci);
    }

    public function clearLowerCi()
    {
        unset($this->lower_ci);
    }

    /**
     * Generated from protobuf field <code>optional double lower_ci = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLowerCi($var)
    {
        GPBUtil::checkDouble($var);
        $this->lower_ci = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double upper_ci = 4;</code>
     * @return float
     */
    public function getUpperCi()
    {
        return isset($this->upper_ci) ? $this->upper_ci : 0.0;
    }

    public function hasUpperCi()
    {
        return isset($this->upper_ci);
    }

    public function clearUpperCi()
    {
        unset($this->upper_ci);
    }

    /**
     * Generated from protobuf field <code>optional double upper_ci = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setUpperCi($var)
    {
        GPBUtil::checkDouble($var);
        $this->upper_ci = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double variance = 5;</code>
     * @return float
     */
    public function getVariance()
    {
        return isset($this->variance) ? $this->variance : 0.0;
    }

    public function hasVariance()
    {
        return isset($this->variance);
    }

    public function clearVariance()
    {
        unset($this->variance);
    }

    /**
     * Generated from protobuf field <code>optional double variance = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setVariance($var)
    {
        GPBUtil::checkDouble($var);
        $this->variance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 seed = 6;</code>
     * @return int|string
     */
    public function getSeed()
    {
        return isset($this->seed) ? $this->seed : 0;
    }

    public function hasSeed()
    {
        return isset($this->seed);
    }

    public function clearSeed()
    {
        unset($this->seed);
    }

    /**
     * Generated from protobuf field <code>optional int64 seed = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeed($var)
    {
        GPBUtil::checkInt64($var);
        $this->seed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool passed = 7;</code>
     * @return bool
     */
    public function getPassed()
    {
        return $this->passed;
    }

    /**
     * Generated from protobuf field <code>bool passed = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setPassed($var)
    {
        GPBUtil::checkBool($var);
        $this->passed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string notes = 8;</code>
     * @return string
     */
    public function getNotes()
    {
        return isset($this->notes) ? $this->notes : '';
    }

    public function hasNotes()
    {
        return isset($this->notes);
    }

    public function clearNotes()
    {
        unset($this->notes);
    }

    /**
     * Generated from protobuf field <code>optional string notes = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 9;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 9;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

}

