<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>string event_type = 2;</code>
     */
    protected $event_type = '';
    /**
     * Generated from protobuf field <code>string timestamp = 3;</code>
     */
    protected $timestamp = '';
    /**
     * Generated from protobuf field <code>string task_id = 4;</code>
     */
    protected $task_id = '';
    /**
     * Generated from protobuf field <code>string status = 5;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>optional string message = 6;</code>
     */
    protected $message = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     */
    protected $extensions = null;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     */
    protected $provenance = null;
    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     */
    private $eval_results;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type string $event_type
     *     @type string $timestamp
     *     @type string $task_id
     *     @type string $status
     *     @type string $message
     *     @type \Google\Protobuf\Struct $extensions
     *     @type \Monarchic\AgentProtocol\V1\Provenance $provenance
     *     @type \Monarchic\AgentProtocol\V1\EvalResult[] $eval_results
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_type = 2;</code>
     * @return string
     */
    public function getEventType()
    {
        return $this->event_type;
    }

    /**
     * Generated from protobuf field <code>string event_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventType($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 3;</code>
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string task_id = 4;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>string task_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 5;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string message = 6;</code>
     * @return string
     */
    public function getMessage()
    {
        return isset($this->message) ? $this->message : '';
    }

    public function hasMessage()
    {
        return isset($this->message);
    }

    public function clearMessage()
    {
        unset($this->message);
    }

    /**
     * Generated from protobuf field <code>optional string message = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 7;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     * @return \Monarchic\AgentProtocol\V1\Provenance|null
     */
    public function getProvenance()
    {
        return $this->provenance;
    }

    public function hasProvenance()
    {
        return isset($this->provenance);
    }

    public function clearProvenance()
    {
        unset($this->provenance);
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.Provenance provenance = 8;</code>
     * @param \Monarchic\AgentProtocol\V1\Provenance $var
     * @return $this
     */
    public function setProvenance($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\Provenance::class);
        $this->provenance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     * @return RepeatedField<\Monarchic\AgentProtocol\V1\EvalResult>
     */
    public function getEvalResults()
    {
        return $this->eval_results;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.EvalResult eval_results = 9;</code>
     * @param \Monarchic\AgentProtocol\V1\EvalResult[] $var
     * @return $this
     */
    public function setEvalResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Monarchic\AgentProtocol\V1\EvalResult::class);
        $this->eval_results = $arr;

        return $this;
    }

}

