<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.ObjectiveSpec</code>
 */
class ObjectiveSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string metric_key = 1;</code>
     */
    protected $metric_key = '';
    /**
     * Generated from protobuf field <code>string direction = 2;</code>
     */
    protected $direction = '';
    /**
     * Generated from protobuf field <code>optional double target = 3;</code>
     */
    protected $target = null;
    /**
     * Generated from protobuf field <code>optional double min_delta = 4;</code>
     */
    protected $min_delta = null;
    /**
     * Generated from protobuf field <code>optional double tolerance = 5;</code>
     */
    protected $tolerance = null;
    /**
     * Generated from protobuf field <code>optional string report_file = 6;</code>
     */
    protected $report_file = null;
    /**
     * Generated from protobuf field <code>optional string report_task_id = 7;</code>
     */
    protected $report_task_id = null;
    /**
     * Generated from protobuf field <code>optional double weight = 8;</code>
     */
    protected $weight = null;
    /**
     * Generated from protobuf field <code>optional string description = 9;</code>
     */
    protected $description = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 10;</code>
     */
    protected $extensions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $metric_key
     *     @type string $direction
     *     @type float $target
     *     @type float $min_delta
     *     @type float $tolerance
     *     @type string $report_file
     *     @type string $report_task_id
     *     @type float $weight
     *     @type string $description
     *     @type \Google\Protobuf\Struct $extensions
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string metric_key = 1;</code>
     * @return string
     */
    public function getMetricKey()
    {
        return $this->metric_key;
    }

    /**
     * Generated from protobuf field <code>string metric_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMetricKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->metric_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string direction = 2;</code>
     * @return string
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * Generated from protobuf field <code>string direction = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDirection($var)
    {
        GPBUtil::checkString($var, True);
        $this->direction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double target = 3;</code>
     * @return float
     */
    public function getTarget()
    {
        return isset($this->target) ? $this->target : 0.0;
    }

    public function hasTarget()
    {
        return isset($this->target);
    }

    public function clearTarget()
    {
        unset($this->target);
    }

    /**
     * Generated from protobuf field <code>optional double target = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkDouble($var);
        $this->target = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double min_delta = 4;</code>
     * @return float
     */
    public function getMinDelta()
    {
        return isset($this->min_delta) ? $this->min_delta : 0.0;
    }

    public function hasMinDelta()
    {
        return isset($this->min_delta);
    }

    public function clearMinDelta()
    {
        unset($this->min_delta);
    }

    /**
     * Generated from protobuf field <code>optional double min_delta = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setMinDelta($var)
    {
        GPBUtil::checkDouble($var);
        $this->min_delta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double tolerance = 5;</code>
     * @return float
     */
    public function getTolerance()
    {
        return isset($this->tolerance) ? $this->tolerance : 0.0;
    }

    public function hasTolerance()
    {
        return isset($this->tolerance);
    }

    public function clearTolerance()
    {
        unset($this->tolerance);
    }

    /**
     * Generated from protobuf field <code>optional double tolerance = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setTolerance($var)
    {
        GPBUtil::checkDouble($var);
        $this->tolerance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string report_file = 6;</code>
     * @return string
     */
    public function getReportFile()
    {
        return isset($this->report_file) ? $this->report_file : '';
    }

    public function hasReportFile()
    {
        return isset($this->report_file);
    }

    public function clearReportFile()
    {
        unset($this->report_file);
    }

    /**
     * Generated from protobuf field <code>optional string report_file = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setReportFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->report_file = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string report_task_id = 7;</code>
     * @return string
     */
    public function getReportTaskId()
    {
        return isset($this->report_task_id) ? $this->report_task_id : '';
    }

    public function hasReportTaskId()
    {
        return isset($this->report_task_id);
    }

    public function clearReportTaskId()
    {
        unset($this->report_task_id);
    }

    /**
     * Generated from protobuf field <code>optional string report_task_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setReportTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->report_task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double weight = 8;</code>
     * @return float
     */
    public function getWeight()
    {
        return isset($this->weight) ? $this->weight : 0.0;
    }

    public function hasWeight()
    {
        return isset($this->weight);
    }

    public function clearWeight()
    {
        unset($this->weight);
    }

    /**
     * Generated from protobuf field <code>optional double weight = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string description = 9;</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->description) ? $this->description : '';
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Generated from protobuf field <code>optional string description = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 10;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 10;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

}

