<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.Provenance</code>
 */
class Provenance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string prompt_sha256 = 1;</code>
     */
    protected $prompt_sha256 = '';
    /**
     * Generated from protobuf field <code>string code_sha256 = 2;</code>
     */
    protected $code_sha256 = '';
    /**
     * Generated from protobuf field <code>repeated string dataset_sha256 = 3;</code>
     */
    private $dataset_sha256;
    /**
     * Generated from protobuf field <code>string runtime = 4;</code>
     */
    protected $runtime = '';
    /**
     * Generated from protobuf field <code>optional string model = 5;</code>
     */
    protected $model = null;
    /**
     * Generated from protobuf field <code>string runner = 6;</code>
     */
    protected $runner = '';
    /**
     * Generated from protobuf field <code>string orchestrator = 7;</code>
     */
    protected $orchestrator = '';
    /**
     * Generated from protobuf field <code>optional string task_spec_sha256 = 8;</code>
     */
    protected $task_spec_sha256 = null;
    /**
     * Generated from protobuf field <code>optional string pipeline_sha256 = 9;</code>
     */
    protected $pipeline_sha256 = null;
    /**
     * Generated from protobuf field <code>optional string command_sha256 = 10;</code>
     */
    protected $command_sha256 = null;
    /**
     * Generated from protobuf field <code>string created_at = 11;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>optional string source_task_id = 12;</code>
     */
    protected $source_task_id = null;
    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 13;</code>
     */
    private $dataset_refs;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 14;</code>
     */
    protected $extensions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $prompt_sha256
     *     @type string $code_sha256
     *     @type string[] $dataset_sha256
     *     @type string $runtime
     *     @type string $model
     *     @type string $runner
     *     @type string $orchestrator
     *     @type string $task_spec_sha256
     *     @type string $pipeline_sha256
     *     @type string $command_sha256
     *     @type string $created_at
     *     @type string $source_task_id
     *     @type \Monarchic\AgentProtocol\V1\DatasetRef[] $dataset_refs
     *     @type \Google\Protobuf\Struct $extensions
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string prompt_sha256 = 1;</code>
     * @return string
     */
    public function getPromptSha256()
    {
        return $this->prompt_sha256;
    }

    /**
     * Generated from protobuf field <code>string prompt_sha256 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPromptSha256($var)
    {
        GPBUtil::checkString($var, True);
        $this->prompt_sha256 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code_sha256 = 2;</code>
     * @return string
     */
    public function getCodeSha256()
    {
        return $this->code_sha256;
    }

    /**
     * Generated from protobuf field <code>string code_sha256 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeSha256($var)
    {
        GPBUtil::checkString($var, True);
        $this->code_sha256 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string dataset_sha256 = 3;</code>
     * @return RepeatedField<string>
     */
    public function getDatasetSha256()
    {
        return $this->dataset_sha256;
    }

    /**
     * Generated from protobuf field <code>repeated string dataset_sha256 = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDatasetSha256($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dataset_sha256 = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string runtime = 4;</code>
     * @return string
     */
    public function getRuntime()
    {
        return $this->runtime;
    }

    /**
     * Generated from protobuf field <code>string runtime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRuntime($var)
    {
        GPBUtil::checkString($var, True);
        $this->runtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string model = 5;</code>
     * @return string
     */
    public function getModel()
    {
        return isset($this->model) ? $this->model : '';
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Generated from protobuf field <code>optional string model = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string runner = 6;</code>
     * @return string
     */
    public function getRunner()
    {
        return $this->runner;
    }

    /**
     * Generated from protobuf field <code>string runner = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRunner($var)
    {
        GPBUtil::checkString($var, True);
        $this->runner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orchestrator = 7;</code>
     * @return string
     */
    public function getOrchestrator()
    {
        return $this->orchestrator;
    }

    /**
     * Generated from protobuf field <code>string orchestrator = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOrchestrator($var)
    {
        GPBUtil::checkString($var, True);
        $this->orchestrator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string task_spec_sha256 = 8;</code>
     * @return string
     */
    public function getTaskSpecSha256()
    {
        return isset($this->task_spec_sha256) ? $this->task_spec_sha256 : '';
    }

    public function hasTaskSpecSha256()
    {
        return isset($this->task_spec_sha256);
    }

    public function clearTaskSpecSha256()
    {
        unset($this->task_spec_sha256);
    }

    /**
     * Generated from protobuf field <code>optional string task_spec_sha256 = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskSpecSha256($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_spec_sha256 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string pipeline_sha256 = 9;</code>
     * @return string
     */
    public function getPipelineSha256()
    {
        return isset($this->pipeline_sha256) ? $this->pipeline_sha256 : '';
    }

    public function hasPipelineSha256()
    {
        return isset($this->pipeline_sha256);
    }

    public function clearPipelineSha256()
    {
        unset($this->pipeline_sha256);
    }

    /**
     * Generated from protobuf field <code>optional string pipeline_sha256 = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPipelineSha256($var)
    {
        GPBUtil::checkString($var, True);
        $this->pipeline_sha256 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string command_sha256 = 10;</code>
     * @return string
     */
    public function getCommandSha256()
    {
        return isset($this->command_sha256) ? $this->command_sha256 : '';
    }

    public function hasCommandSha256()
    {
        return isset($this->command_sha256);
    }

    public function clearCommandSha256()
    {
        unset($this->command_sha256);
    }

    /**
     * Generated from protobuf field <code>optional string command_sha256 = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCommandSha256($var)
    {
        GPBUtil::checkString($var, True);
        $this->command_sha256 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 11;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string source_task_id = 12;</code>
     * @return string
     */
    public function getSourceTaskId()
    {
        return isset($this->source_task_id) ? $this->source_task_id : '';
    }

    public function hasSourceTaskId()
    {
        return isset($this->source_task_id);
    }

    public function clearSourceTaskId()
    {
        unset($this->source_task_id);
    }

    /**
     * Generated from protobuf field <code>optional string source_task_id = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 13;</code>
     * @return RepeatedField<\Monarchic\AgentProtocol\V1\DatasetRef>
     */
    public function getDatasetRefs()
    {
        return $this->dataset_refs;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.DatasetRef dataset_refs = 13;</code>
     * @param \Monarchic\AgentProtocol\V1\DatasetRef[] $var
     * @return $this
     */
    public function setDatasetRefs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Monarchic\AgentProtocol\V1\DatasetRef::class);
        $this->dataset_refs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 14;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 14;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

}

