<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.Task</code>
 */
class Task extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>string task_id = 2;</code>
     */
    protected $task_id = '';
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     */
    protected $role = 0;
    /**
     * Generated from protobuf field <code>string goal = 4;</code>
     */
    protected $goal = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct inputs = 5;</code>
     */
    protected $inputs = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct constraints = 6;</code>
     */
    protected $constraints = null;
    /**
     * Generated from protobuf field <code>repeated string gates_required = 7;</code>
     */
    private $gates_required;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     */
    protected $run_context = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 9;</code>
     */
    protected $extensions = null;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 10;</code>
     */
    protected $experiment_spec = null;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.DeliveryContract delivery_contract = 11;</code>
     */
    protected $delivery_contract = null;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ObjectiveSpec objective_spec = 12;</code>
     */
    protected $objective_spec = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type string $task_id
     *     @type int $role
     *     @type string $goal
     *     @type \Google\Protobuf\Struct $inputs
     *     @type \Google\Protobuf\Struct $constraints
     *     @type string[] $gates_required
     *     @type \Monarchic\AgentProtocol\V1\RunContext $run_context
     *     @type \Google\Protobuf\Struct $extensions
     *     @type \Monarchic\AgentProtocol\V1\ExperimentSpec $experiment_spec
     *     @type \Monarchic\AgentProtocol\V1\DeliveryContract $delivery_contract
     *     @type \Monarchic\AgentProtocol\V1\ObjectiveSpec $objective_spec
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string task_id = 2;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>string task_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.AgentRole role = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Monarchic\AgentProtocol\V1\AgentRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string goal = 4;</code>
     * @return string
     */
    public function getGoal()
    {
        return $this->goal;
    }

    /**
     * Generated from protobuf field <code>string goal = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGoal($var)
    {
        GPBUtil::checkString($var, True);
        $this->goal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct inputs = 5;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getInputs()
    {
        return $this->inputs;
    }

    public function hasInputs()
    {
        return isset($this->inputs);
    }

    public function clearInputs()
    {
        unset($this->inputs);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct inputs = 5;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setInputs($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->inputs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct constraints = 6;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getConstraints()
    {
        return $this->constraints;
    }

    public function hasConstraints()
    {
        return isset($this->constraints);
    }

    public function clearConstraints()
    {
        unset($this->constraints);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct constraints = 6;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setConstraints($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->constraints = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string gates_required = 7;</code>
     * @return RepeatedField<string>
     */
    public function getGatesRequired()
    {
        return $this->gates_required;
    }

    /**
     * Generated from protobuf field <code>repeated string gates_required = 7;</code>
     * @param string[] $var
     * @return $this
     */
    public function setGatesRequired($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->gates_required = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     * @return \Monarchic\AgentProtocol\V1\RunContext|null
     */
    public function getRunContext()
    {
        return $this->run_context;
    }

    public function hasRunContext()
    {
        return isset($this->run_context);
    }

    public function clearRunContext()
    {
        unset($this->run_context);
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.RunContext run_context = 8;</code>
     * @param \Monarchic\AgentProtocol\V1\RunContext $var
     * @return $this
     */
    public function setRunContext($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\RunContext::class);
        $this->run_context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 9;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 9;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 10;</code>
     * @return \Monarchic\AgentProtocol\V1\ExperimentSpec|null
     */
    public function getExperimentSpec()
    {
        return $this->experiment_spec;
    }

    public function hasExperimentSpec()
    {
        return isset($this->experiment_spec);
    }

    public function clearExperimentSpec()
    {
        unset($this->experiment_spec);
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ExperimentSpec experiment_spec = 10;</code>
     * @param \Monarchic\AgentProtocol\V1\ExperimentSpec $var
     * @return $this
     */
    public function setExperimentSpec($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\ExperimentSpec::class);
        $this->experiment_spec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.DeliveryContract delivery_contract = 11;</code>
     * @return \Monarchic\AgentProtocol\V1\DeliveryContract|null
     */
    public function getDeliveryContract()
    {
        return $this->delivery_contract;
    }

    public function hasDeliveryContract()
    {
        return isset($this->delivery_contract);
    }

    public function clearDeliveryContract()
    {
        unset($this->delivery_contract);
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.DeliveryContract delivery_contract = 11;</code>
     * @param \Monarchic\AgentProtocol\V1\DeliveryContract $var
     * @return $this
     */
    public function setDeliveryContract($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\DeliveryContract::class);
        $this->delivery_contract = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ObjectiveSpec objective_spec = 12;</code>
     * @return \Monarchic\AgentProtocol\V1\ObjectiveSpec|null
     */
    public function getObjectiveSpec()
    {
        return $this->objective_spec;
    }

    public function hasObjectiveSpec()
    {
        return isset($this->objective_spec);
    }

    public function clearObjectiveSpec()
    {
        unset($this->objective_spec);
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ObjectiveSpec objective_spec = 12;</code>
     * @param \Monarchic\AgentProtocol\V1\ObjectiveSpec $var
     * @return $this
     */
    public function setObjectiveSpec($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\ObjectiveSpec::class);
        $this->objective_spec = $var;

        return $this;
    }

}

